export default [{
    "title": "Smiley Face Emojis",
    "charSet": [
        { "c": "🙂", "d": "Slightly smiling face" },
        { "c": "😀", "d": "Smiling face" },
        { "c": "😃", "d": "Smiling face with big eyes" },
        { "c": "😄", "d": "Smiling face with smiling eyes" },
        { "c": "😁", "d": "Beaming face with smiling eyes" },
        { "c": "😅", "d": "Smiling face with tears" },
        { "c": "😆", "d": "Grinning face" },
        { "c": "🤣", "d": "Rolling on the floor laughing" },
        { "c": "😂", "d": "Lauging with tears" },
        { "c": "🙃", "d": "Upside down face" },
        { "c": "😉", "d": "Winking face" },
        { "c": "😊", "d": "Smiling face with smiling eyes" },
        { "c": "😇", "d": "Smiling face with halo" },
        { "c": "😎", "d": "Smiling face with sunglasses" },
        { "c": "🤓", "d": "Nerdy face" },
        { "c": "🧐", "d": "Face with monocle" },
        { "c": "🥳", "d": "Partying face" }
    ]
}, {
    "title": "Emotional Faces Emojis",
    "charSet": [
        { "c": "🥰", "d": "Smiling face with hearts" },
        { "c": "😍", "d": "Smiling face with heart eyes" },
        { "c": "🤩", "d": "Star-struck" },
        { "c": "😘", "d": "Face blowing kiss" },
        { "c": "😗", "d": "Kissing face" },
        { "c": "☺", "d": "Smiling face" },
        { "c": "😚", "d": "Kissing face with closed eyes" },
        { "c": "😙", "d": "Kissng face with smiling eyes" },
        { "c": "🥲", "d": "Smiling face with tears" }
    ]
}, {
    "title": "Faces with Tongue Emojis",
    "charSet": [
        { "c": "😋", "d": "Yummy face" },
        { "c": "😛", "d": "Face with tongue" },
        { "c": "😜", "d": "WInking face with tongue" },
        { "c": "🤪", "d": "Zany face" },
        { "c": "😝", "d": "Squinting face with tongue" },
        { "c": "🤑", "d": "Money face with money tongue" }
    ]
}, {
    "title": "Faces with Hands Emojis",
    "charSet": [
        { "c": "🤗", "d": "Hugs" },
        { "c": "🤭", "d": "Face with hand in mouth" },
        { "c": "🤫", "d": "Shushing face" },
        { "c": "🤔", "d": "Thinking face" }
    ]
},
{
    "title": "Neutral Faces Emojis",
    "charSet": [
        { "c": "😐", "d": "Neutral face" },
        { "c": "🤐", "d": "Zipped mouth" },
        { "c": "🤨", "d": "Face with raised eyebrow" },
        { "c": "😑", "d": "Expressionless face" },
        { "c": "😶", "d": "Face with no mouth" },
        { "c": "😏", "d": "Smirking face" },
        { "c": "😒", "d": "Unamused face" },
        { "c": "🙄", "d": "Face with rolling eyes" },
        { "c": "😬", "d": "Grimacing face" },
        { "c": "🤥", "d": "Lying face" }
    ]
},
{
    "title": "Sleepy Faces Emojis",
    "charSet": [
        { "c": "😪", "d": "Sleepy face" },
        { "c": "😴", "d": "Sleeping face" },
        { "c": "😌", "d": "Relieved face" },
        { "c": "😔", "d": "Pensive face" },
        { "c": "🤤", "d": "Drooling face" }
    ]
},
{
    "title": "Sick Faces Emojis",
    "charSet": [
        { "c": "😷", "d": "Face with mask" },
        { "c": "🤒", "d": "Face with thermometer" },
        { "c": "🤕", "d": "Face with bandage" },
        { "c": "🤢", "d": "Nauseous face" },
        { "c": "🤮", "d": "Vomiting face" },
        { "c": "🤧", "d": "Sneezing face" },
        { "c": "🥵", "d": "Hot face" },
        { "c": "🥶", "d": "Cold face" },
        { "c": "🥴", "d": "Woozy face" },
        { "c": "😵", "d": "Face with crossed-out eyes" },
        { "c": "🤯", "d": "Face with exploding head" }
    ]
},
{
    "title": "Concerned Faces Emojis",
    "charSet": [
        { "c": "😕", "d": "Confused face" },
        { "c": "😟", "d": "Worried face" },
        { "c": "🙁", "d": "Slightly frowning face" },
        { "c": "☹", "d": "Frowning face" },
        { "c": "😮", "d": "Face with open mouth" },
        { "c": "😯", "d": "Hushed face" },
        { "c": "😲", "d": "Astonished face" },
        { "c": "😳", "d": "Flushed face" },
        { "c": "🥺", "d": "Begging face" },
        { "c": "😦", "d": "Frowning face with open mouth" },
        { "c": "😧", "d": "Angushed face" },
        { "c": "😨", "d": "Fearful face" },
        { "c": "😰", "d": "Anxious face with sweat" },
        { "c": "😥", "d": "Sad but relieved face" },
        { "c": "😢", "d": "Crying face" },
        { "c": "😭", "d": "Loudly crying face" },
        { "c": "😱", "d": "Screaming face" },
        { "c": "😖", "d": "Confounded face" },
        { "c": "😣", "d": "Persevering face" },
        { "c": "😞", "d": "Disappointed face" },
        { "c": "😓", "d": "Downcast face with sweat" },
        { "c": "😩", "d": "Weary face" },
        { "c": "😫", "d": "Tired face" },
        { "c": "🥱", "d": "Yawning face" }
    ]
},
{
    "title": "Negative Faces Emojis",
    "charSet": [
        { "c": "😤", "d": "Face with steam" },
        { "c": "😡", "d": "Pouting face" },
        { "c": "😠", "d": "Angry face" },
        { "c": "🤬", "d": "Face with symbols on mouth" },
        { "c": "😈", "d": "Smiling face with horns" },
        { "c": "👿", "d": "Angry face with horns" },
        { "c": "💀", "d": "Skull" },
        { "c": "☠", "d": "Skull and cross-bone" }
    ]
},
{
    "title": "Costume Faces Emojis",
    "charSet": [
        { "c": "💩", "d": "Pile of poo" },
        { "c": "🤡", "d": "Clown" },
        { "c": "👹", "d": "Ogre" },
        { "c": "👺", "d": "Goblin" },
        { "c": "👻", "d": "Ghost" },
        { "c": "👽", "d": "Alien" },
        { "c": "👾", "d": "Alien monster" },
        { "c": "🤖", "d": "Robot" }
    ]
},
{
    "title": "Faces that require more than one unicode character",
    "charSet": [
        { "c": "😶‍🌫️", "d": "Face in clouds" },
        { "c": "😮‍💨", "d": "Face exhaling" },
        { "c": "😵‍💫", "d": "Face with spiral eyes" },
        { "c": "🧔‍♂️", "d": "Man with beard" },
        { "c": "🧔‍♀️", "d": "Woman with beard" },
        { "c": "👨‍🦰", "d": "Man with red hair" },
        { "c": "👨‍🦱", "d": "Man with curly hair" },
        { "c": "👨‍🦳", "d": "Man with white hair" },
        { "c": "👨‍🦲", "d": "Man with bald head" },
        { "c": "👩‍🦰", "d": "Woman with red hair" },
        { "c": "🧑‍🦰", "d": "Person with red hair" },
        { "c": "👩‍🦱", "d": "Woman with curly hair" },
        { "c": "🧑‍🦱", "d": "Person with curly hair" },
        { "c": "👩‍🦳", "d": "Woman with white hair" },
        { "c": "🧑‍🦳", "d": "Person with white hair" },
        { "c": "👩‍🦲", "d": "Woman with bald head" },
        { "c": "🧑‍🦲", "d": "Person with bald head" },
        { "c": "👱‍♀️", "d": "Woman with blond hair" },
        { "c": "👱‍♂️", "d": "Man with blond hair" }
    ]
},
{
    "title": "Cat Faces Emojis",
    "charSet": [
        { "c": "😺", "d": "Grinnig cat" },
        { "c": "😸", "d": "Grinning cat with smiling eyes" },
        { "c": "😹", "d": "Grinning cat with tears" },
        { "c": "😻", "d": "Smiling cat with heart eyes" },
        { "c": "😼", "d": "Cat with wry smile" },
        { "c": "😽", "d": "Kissing cat" },
        { "c": "🙀", "d": "Weary cat" },
        { "c": "😿", "d": "Crying cat" },
        { "c": "😾", "d": "Pouting cat" }
    ]
},
{
    "title": "Monkey Faces Emojis",
    "charSet": [
        { "c": "🙈", "d": "See no evil monkey" },
        { "c": "🙉", "d": "Hear no evil monkey" },
        { "c": "🙊", "d": "Speak no evil monkey" }
    ]
},
{
    "title": "Emotion Emojis",
    "charSet": [
        { "c": "💋", "d": "Kiss" },
        { "c": "💌", "d": "Love letter" },
        { "c": "💘", "d": "Heart with arrow" },
        { "c": "💝", "d": "Heart with ribbon" },
        { "c": "💖", "d": "Sparking heart" },
        { "c": "💗", "d": "Growing heart" },
        { "c": "💓", "d": "Beating heart" },
        { "c": "💞", "d": "Revolving heart" },
        { "c": "💕", "d": "Two hearts" },
        { "c": "💟", "d": "Heart decoration" },
        { "c": "❣", "d": "Heart exclamation" },
        { "c": "💔", "d": "Broken heart" },
        { "c": "❤️‍🔥", "d": "Heart on fire" },
        { "c": "❤️‍🩹", "d": "Mending heart" },
        { "c": "❤", "d": "Red heart" },
        { "c": "🧡", "d": "Orange heart" },
        { "c": "💛", "d": "Yellow heart" },
        { "c": "💚", "d": "Green heart" },
        { "c": "💙", "d": "Blue heart" },
        { "c": "💜", "d": "Purple heart" },
        { "c": "🤎", "d": "Brown heart" },
        { "c": "🖤", "d": "Black heart" },
        { "c": "🤍", "d": "White heart" },
        { "c": "💯", "d": "Hundred(correct)" },
        { "c": "💢", "d": "Anger" },
        { "c": "💥", "d": "Collision" },
        { "c": "💫", "d": "Dizzy" },
        { "c": "💦", "d": "Sweat droplets" },
        { "c": "💨", "d": "Dashing away" },
        { "c": "🕳", "d": "Hole" },
        { "c": "💣", "d": "Bomb" },
        { "c": "💬", "d": "Message baloon" },
        { "c": "👁️‍🗨️", "d": "Eye in speech bubble" },
        { "c": "🗨", "d": "Left speech bubble" },
        { "c": "🗯", "d": "Anger bubble" },
        { "c": "💭", "d": "Thought baloon" },
        { "c": "💤", "d": "zzz" }
    ]
},
{
    "title": "Hands and other Body Parts Emojis",
    "charSet": [
        { "c": "👋", "d": "Waving hand" },
        { "c": "🤚", "d": "Raised back of hand" },
        { "c": "🖐", "d": "Hands with splayed finger" },
        { "c": "✋", "d": "Raised hand" },
        { "c": "🖖", "d": "Vulcan salute" },
        { "c": "👌", "d": "Ok" },
        { "c": "🤌", "d": "Pinched fingers" },
        { "c": "🤏", "d": "Pinched hand" },
        { "c": "✌", "d": "Victory hand" },
        { "c": "🤞", "d": "Crossed fingers" },
        { "c": "🤟", "d": "Love you" },
        { "c": "🤘", "d": "Horn sign" },
        { "c": "🤙", "d": "Call me hand" },
        { "c": "👈", "d": "Index finger pointing left" },
        { "c": "👉", "d": "Index finger pointing right" },
        { "c": "👆", "d": "Index finger pointing up" },
        { "c": "👇", "d": "Index finger pointing down" },
        { "c": "🖕", "d": "Middle finger" },
        { "c": "☝", "d": "Forehand Index finger pointing up" },
        { "c": "🫵", "d": "Index finger pointing at viewer" },
        { "c": "👍", "d": "Thumbs up" },
        { "c": "👎", "d": "Thumbs down" },
        { "c": "✊", "d": "Raised fist" },
        { "c": "👊", "d": "Fist" },
        { "c": "🤛", "d": "Left facing fist" },
        { "c": "🤜", "d": "Right facing fist" },
        { "c": "👏", "d": "Clapping hands" },
        { "c": "🙌", "d": "Raised hands" },
        { "c": "👐", "d": "Open hands" },
        { "c": "🤲", "d": "Palms together hands" },
        { "c": "🤝", "d": "Handshake" },
        { "c": "🙏", "d": "Praying hands" },
        { "c": "✍", "d": "Writing hands" },
        { "c": "💅", "d": "Nail polish" },
        { "c": "🤳", "d": "Selfie hand" },
        { "c": "💪", "d": "Flexed biceps" },
        { "c": "🦾", "d": "Mechanical arm" },
        { "c": "🦵", "d": "Leg" },
        { "c": "🦿", "d": "Mechanical leg" },
        { "c": "🦶", "d": "Foot" },
        { "c": "👂", "d": "Ear" },
        { "c": "🦻", "d": "Ear with earing aid" },
        { "c": "👃", "d": "Nose" },
        { "c": "🧠", "d": "Brain" },
        { "c": "👣", "d": "Footprint" },
        { "c": "🫀", "d": "Mechanical heart" },
        { "c": "🫁", "d": "Lungs" },
        { "c": "🦷", "d": "Tooth" },
        { "c": "🦴", "d": "Bone" },
        { "c": "👀", "d": "Eyes" },
        { "c": "👁", "d": "Eye" },
        { "c": "👅", "d": "Nose" },
        { "c": "👄", "d": "Mouth" }
    ]
},
{
    "title": "Person Emojis",
    "charSet": [
        { "c": "🧑", "d": "Person" },
        { "c": "👶", "d": "Baby" },
        { "c": "🧒", "d": "Child" },
        { "c": "👦", "d": "Boy" },
        { "c": "👧", "d": "Girl" },
        { "c": "👱", "d": "Person with blonde hair" },
        { "c": "👨", "d": "Man" },
        { "c": "🧔", "d": "Bearded person" },
        { "c": "🧔‍♂‍", "d": "Bearded man" },
        { "c": "🧔‍♀‍", "d": "Bearded woman" },
        { "c": "👨‍🦰", "d": "Man with red hair" },
        { "c": "👨‍🦱", "d": "Man with curly hair" },
        { "c": "👨‍🦳", "d": "Man with white hair" },
        { "c": "👨‍🦲", "d": "Bald man" },
        { "c": "👩", "d": "Woman" },
        { "c": "👩‍🦰", "d": "Woman with red hair" },
        { "c": "👩‍🦱", "d": "Woman with curly hair" },
        { "c": "👩‍🦳", "d": "Woman with white hair" },
        { "c": "👩‍🦲", "d": "Bald woman" },
        { "c": "👱‍♀‍", "d": "Woman with blonde hair" },
        { "c": "👱‍♂‍", "d": "Man with blonde hair" },
        { "c": "🧓", "d": "Old person" },
        { "c": "👴", "d": "Old man" },
        { "c": "👵", "d": "Old woman" },
        { "c": "🙍", "d": "Person frowning" },
        { "c": "🙍‍♂️", "d": "Man frowning" },
        { "c": "🙍‍♀️", "d": "Woman frowning" },
        { "c": "🙎‍♂️", "d": "Man pouting" },
        { "c": "🙎‍♀️", "d": "Woman pouting" },
        { "c": "🙅‍♂️", "d": "Man gesturing no" },
        { "c": "🙅‍♀️", "d": "Woman gesturing no" },
        { "c": "🙆‍♂️", "d": "Man gesturing ok" },
        { "c": "🙆‍♀️", "d": "Woman gesturing ok" },
        { "c": "💁‍♂️", "d": "Man tipping hand" },
        { "c": "💁‍♀️", "d": "Woman tipping hand" },
        { "c": "🙋‍♂️", "d": "Man raising hand" },
        { "c": "🙋‍♀️", "d": "Woman raising hand" },
        { "c": "🧏‍♂️", "d": "Deaf man" },
        { "c": "🧏‍♀️", "d": "Deaf woman" },
        { "c": "🙇‍♂️", "d": "Man bowing" },
        { "c": "🙇‍♀️", "d": "Woman bowing" },
        { "c": "🤦‍♂️", "d": "Man facepalming" },
        { "c": "🤦‍♀️", "d": "Woman facepalming" },
        { "c": "🤷‍♂️", "d": "Man shrugging" },
        { "c": "🤷‍♀️", "d": "Woman shrugging" },
        { "c": "🧑‍⚕️", "d": "Health worker" },
        { "c": "👨‍⚕️", "d": "Man health worker" },
        { "c": "👩‍⚕️", "d": "Woman health worker" },
        { "c": "🧑‍🎓", "d": "Student" },
        { "c": "👨‍🎓", "d": "Man student" },
        { "c": "👩‍🎓", "d": "Woman student" },
        { "c": "🧑‍🏫", "d": "Teacher" },
        { "c": "👨‍🏫", "d": "Man teacher" },
        { "c": "👩‍🏫", "d": "Woman teacher" },
        { "c": "🧑‍⚖️", "d": "Judge" },
        { "c": "👩‍⚖️", "d": "Woman judge" },
        { "c": "🧑‍🌾", "d": "Farmer" },
        { "c": "👨‍🌾", "d": "Man farmer" },
        { "c": "👩‍🌾", "d": "Woman farmer" },
        { "c": "🧑‍🍳", "d": "Cook" },
        { "c": "👨‍🍳", "d": "Man cook" },
        { "c": "👩‍🍳", "d": "Woman cook" },
        { "c": "🧑‍🔧", "d": "Mechanic" },
        { "c": "👨‍🔧", "d": "Man mechanic" },
        { "c": "👩‍🔧", "d": "Woman mechanic" },
        { "c": "🧑‍🏭", "d": "Factory worker" },
        { "c": "👨‍🏭", "d": "Man factory worker" },
        { "c": "👩‍🏭", "d": "Woman factory worker" },
        { "c": "🧑‍💼", "d": "Office worker" },
        { "c": "👨‍💼", "d": "Man office worker" },
        { "c": "👩‍💼", "d": "Woman factory worker" },
        { "c": "🧑‍🔬", "d": "Scientist" },
        { "c": "👨‍🔬", "d": "Man scientist" },
        { "c": "👩‍🔬", "d": "Woman scientist" },
        { "c": "🧑‍💻", "d": "Technologist" },
        { "c": "👨‍💻", "d": "Man technologist" },
        { "c": "👩‍💻", "d": "Woman technologist" },
        { "c": "🧑‍🎤", "d": "Singer" },
        { "c": "👨‍🎤", "d": "Man singer" },
        { "c": "👩‍🎤", "d": "Woman singer" },
        { "c": "🧑‍🎨", "d": "Artist" },
        { "c": "👨‍🎨", "d": "Man artist" },
        { "c": "👩‍🎨", "d": "Woman artist" },
        { "c": "🧑‍✈️", "d": "Pilot" },
        { "c": "👨‍✈️", "d": "Man pilot" },
        { "c": "👩‍✈️", "d": "Woman pilot" },
        { "c": "🧑‍🚀", "d": "Astronaut" },
        { "c": "👨‍🚀", "d": "Man astronaut" },
        { "c": "👩‍🚀", "d": "Womanh astronaut" },
        { "c": "🧑‍🚒", "d": "Firefighter" },
        { "c": "👨‍🚒", "d": "Man firefighter" },
        { "c": "👩‍🚒", "d": "Woman firefighter" },
        { "c": "👮‍♂️", "d": "Man police" },
        { "c": "👮‍♀️", "d": "Woman police" },
        { "c": "🕵️‍♂️", "d": "Man detective" },
        { "c": "🕵️‍♀️", "d": "Woman detective" },
        { "c": "💂‍♂️", "d": "Man guard" },
        { "c": "💂‍♀️", "d": "Woman guard" },
        { "c": "👷‍♂️", "d": "Man construction worker" },
        { "c": "👷‍♀️", "d": "Woman construction worker" },
        { "c": "👳‍♂️", "d": "Man wearing turban" },
        { "c": "👳‍♀️", "d": "Woman wearing turban" },
        { "c": "🤵‍♂️", "d": "Man in tuxedo" },
        { "c": "🤵‍♀️", "d": "Woman in tuxedo" },
        { "c": "👰‍♂️", "d": "Man with veil" },
        { "c": "👰‍♀️", "d": "Woman with veil" },
        { "c": "🧑‍🍼", "d": "Person feeding baby" },
        { "c": "👩‍🍼", "d": "Woman feeding baby" },
        { "c": "👨‍🍼", "d": "Man feeding baby" },
        { "c": "🧑‍🎄", "d": "Mx claus" },
        { "c": "🦸‍♂️", "d": "Man superhero" },
        { "c": "🦸‍♀️", "d": "Woman superhero" },
        { "c": "🦹‍♂️", "d": "Man supervillain" },
        { "c": "🦹‍♀️", "d": "Woman supervillain" },
        { "c": "🧙‍♂️", "d": "Man mage" },
        { "c": "🧙‍♀️", "d": "Woman mage" },
        { "c": "🧚‍♂️", "d": "Man fairy" },
        { "c": "🧚‍♀️", "d": "Woman fairy" },
        { "c": "🧛‍♂️", "d": "Man vampire" },
        { "c": "🧛‍♀️", "d": "Woman vampire" },
        { "c": "🧜‍♂️", "d": "Merman" },
        { "c": "🧜‍♀️", "d": "Mermaid" },
        { "c": "🧝‍♂️", "d": "Man elf" },
        { "c": "🧝‍♀️", "d": "Woman elf" },
        { "c": "🧞‍♂️", "d": "Man genie" },
        { "c": "🧞‍♀️", "d": "Woman genie" },
        { "c": "🧟‍♂️", "d": "Man zombie" },
        { "c": "🧟‍♀️", "d": "Woman zombie" },
        { "c": "💆‍♂️", "d": "Man getting massage" },
        { "c": "💆‍♀️", "d": "Woman getting massage" },
        { "c": "💇‍♂️", "d": "Man getting haircut" },
        { "c": "💇‍♀️", "d": "Woman getting haircut" },
        { "c": "🚶‍♂️", "d": "Man walking" },
        { "c": "🚶‍♀️", "d": "Woman walking" },
        { "c": "🧍‍♂️", "d": "Man standing" },
        { "c": "🧍‍♀️", "d": "Woman standing" },
        { "c": "🧎‍♂️", "d": "Man kneeling" },
        { "c": "🧎‍♀️", "d": "Woman kneeling" },
        { "c": "🧑‍🦯", "d": "Person with white cane" },
        { "c": "👨‍🦯", "d": "Man with white cane" },
        { "c": "👩‍🦯", "d": "Woman with white cane" },
        { "c": "🧑‍🦼", "d": "Person with motorized wheelchair" },
        { "c": "👨‍🦼", "d": "Man in motorized wheelchair" },
        { "c": "👩‍🦼", "d": "Woman in motorized wheelchair" },
        { "c": "🧑‍🦽", "d": "Person in manual wheelchair" },
        { "c": "👨‍🦽", "d": "Man in manual wheelchair" },
        { "c": "👩‍🦽", "d": "Woman in manual wheelchair" },
        { "c": "🏃‍♂️", "d": "Man running" },
        { "c": "🏃‍♀️", "d": "Woman running" },
        { "c": "👯‍♂️", "d": "Men with bunny ears" },
        { "c": "👯‍♀️", "d": "Women with bunny ears" },
        { "c": "🧖‍♂️", "d": "Man in steamy room" },
        { "c": "🧖‍♀️", "d": "Woman in steamy room" },
        { "c": "🧗‍♂️", "d": "Man climbing" },
        { "c": "🧗‍♀️", "d": "Woman climbing" },
        { "c": "🏌️‍♂️", "d": "Man golfing" },
        { "c": "🏌️‍♀️", "d": "Woman golfing" },
        { "c": "🧗", "d": "Person climbing" },
        { "c": "🧗‍♂‍", "d": "Man climbing" },
        { "c": "🧗‍♀‍", "d": "Woman climbing" },
        { "c": "🤺", "d": "Person fencing" },
        { "c": "🏇", "d": "Horse racing" },
        { "c": "⛷", "d": "Skier" },
        { "c": "🏂", "d": "Snowboarder" },
        { "c": "🏌", "d": "Person playing golf" },
        { "c": "🏌️‍♂‍", "d": "Man playing golf" },
        { "c": "🏌️‍♀‍", "d": "Woman playing golf" },
        { "c": "🏄", "d": "Person surfing" },
        { "c": "🏄‍♂️", "d": "Man sufing" },
        { "c": "🏄‍♀️", "d": "Woman surfing" },
        { "c": "🚣", "d": "Person rowing boat" },
        { "c": "🚣‍♂️", "d": "Man rowing boat" },
        { "c": "🚣‍♀️", "d": "Woman rowing boat" },
        { "c": "🏊", "d": "Person swimming" },
        { "c": "🏊‍♂️", "d": "Man swimming" },
        { "c": "🏊‍♀️", "d": "Woman swimming" },
        { "c": "⛹", "d": "Person bouncing ball" },
        { "c": "⛹️‍♂️", "d": "Man bouncing ball" },
        { "c": "⛹️‍♀️", "d": "Woman bouncing ball" },
        { "c": "🏋", "d": "Person lifting weight" },
        { "c": "🏋️‍♂️", "d": "Man lifting weights" },
        { "c": "🏋️‍♀️", "d": "Woman lifting weights" },
        { "c": "🚴", "d": "Person cycling" },
        { "c": "🚴‍♂️", "d": "Man cycling" },
        { "c": "🚴‍♀️", "d": "Woman cycling" },
        { "c": "🚵", "d": "Person mountain biking" },
        { "c": "🚵‍♂️", "d": "Man mountain biking" },
        { "c": "🚵‍♀️", "d": "Woman mountain biking" },
        { "c": "🤸", "d": "Person cartwheeling" },
        { "c": "🤸‍♂️", "d": "Man cartwheeling" },
        { "c": "🤸‍♀️", "d": "Woman cartwheeling" },
        { "c": "🤼", "d": "People wrestling" },
        { "c": "🤼‍♂️", "d": "Men wrestling" },
        { "c": "🤼‍♀️", "d": "Women wrestling" },
        { "c": "🤽", "d": "Person playing water polo" },
        { "c": "🤽‍♂️", "d": "Man playing water polo" },
        { "c": "🤽‍♀️", "d": "Woman playing water polo" },
        { "c": "🤾", "d": "Person playing handball" },
        { "c": "🤾‍♂️", "d": "Man playing handball" },
        { "c": "🤾‍♀️", "d": "Woman playing handblall" },
        { "c": "🤹", "d": "Person juggling" },
        { "c": "🤹‍♂️", "d": "Man juggling" },
        { "c": "🤹‍♀️", "d": "Woman juggling" },
        { "c": "🧘", "d": "Person lotus position" },
        { "c": "🧘‍♂️", "d": "Man in lotus position" },
        { "c": "🧘‍♀️", "d": "Woman in lotus position" },
        { "c": "🛀", "d": "Person bathing" },
        { "c": "🛌", "d": "Person in bed" }
    ]
},
{
    "title": "Family Emojis",
    "charSet": [
        { "c": "👪", "d": "Family" },
        { "c": "👨‍👩‍👦", "d": "Family of man, woman and boy" },
        { "c": "👨‍👩‍👧", "d": "Family of man, woman and girl" },
        { "c": "👨‍👩‍👧‍👦", "d": "Family of man, woman, boy, and girl" },
        { "c": "👨‍👩‍👦‍👦", "d": "Family of man, woman, boy, and boy" },
        { "c": "👨‍👩‍👧‍👧", "d": "Family of man, woman, girl, and girl" },
        { "c": "👨‍👨‍👦", "d": "Family of man, man, and boy" },
        { "c": "👨‍👨‍👧", "d": "Family of man, man, and girl" },
        { "c": "👨‍👨‍👧‍👦", "d": "Family of man, man, girl, and boy" },
        { "c": "👨‍👨‍👦‍👦", "d": "Family of man, man, boy, and boy" },
        { "c": "👨‍👨‍👧‍👧", "d": "Family of man, man, girl, and girl" },
        { "c": "👩‍👩‍👦", "d": "Family of woman, woman, and boy" },
        { "c": "👩‍👩‍👧", "d": "Family of woman, woman, and girl" },
        { "c": "👩‍👩‍👧‍👦", "d": "Family of woman, woman, girl, and boy" },
        { "c": "👩‍👩‍👦‍👦", "d": "Family of woman, woman, boy, and boy" },
        { "c": "👩‍👩‍👧‍👧", "d": "Family of woman, woman, girl, and girl" },
        { "c": "👨‍👦", "d": "Family of man and boy" },
        { "c": "👨‍👦‍👦", "d": "Family of man, boy, and boy" },
        { "c": "👨‍👧", "d": "Family of man and girl" },
        { "c": "👨‍👧‍👦", "d": "Family of man, girl, and boy" },
        { "c": "👨‍👧‍👧", "d": "Family of man, girl, and girl" },
        { "c": "👩‍👦", "d": "Family of woman, and boy" },
        { "c": "👩‍👦‍👦", "d": "Family of woman, boy, and boy" },
        { "c": "👩‍👧", "d": "Family of woman, and girl" },
        { "c": "👩‍👧‍👦", "d": "Family of woman, girl, and boy" },
        { "c": "👩‍👧‍👧", "d": "Family of woman, girl, and girl" },
        { "c": "🧑‍🤝‍🧑", "d": "People holding hands" },
        { "c": "👭", "d": "Women holding hands" },
        { "c": "👫", "d": "Woman and man holding hands" },
        { "c": "👬", "d": "Men holding hands" },
        { "c": "💏", "d": "Kiss" },
        { "c": "👩‍❤️‍💋‍👨", "d": "Woman and man kissing" },
        { "c": "👨‍❤️‍💋‍👨", "d": "Man and man kissing" },
        { "c": "👩‍❤️‍💋‍👩", "d": "Woman and woman kissing" },
        { "c": "👩‍❤️‍👨", "d": "Woman and man couple" },
        { "c": "👨‍❤️‍👨", "d": "Man and man couple" },
        { "c": "👩‍❤️‍👩", "d": "Woman and woman couple" },
        { "c": "💑", "d": "Couple with heart" },
        { "c": "🗣", "d": "Person speaking" },
        { "c": "👤", "d": "Bust in silhouhette" },
        { "c": "👥", "d": "Busts in silhouette" },
        { "c": "🫂", "d": "People hugging" }
    ]
},
{
    "title": "Animals and Nature Emojis",
    "charSet": [
        { "c": "🐵", "d": "Monkey face" },
        { "c": "🐒", "d": "Monkey" },
        { "c": "🦍", "d": "Gorilla" },
        { "c": "🦧", "d": "Orangutan" },
        { "c": "🐶", "d": "Dog face" },
        { "c": "🐕", "d": "Dog" },
        { "c": "🦮", "d": "Guide dog" },
        { "c": "🐕‍🦺", "d": "Service dog" },
        { "c": "🐩", "d": "Poodle" },
        { "c": "🐺", "d": "Wolf" },
        { "c": "🦊", "d": "Fox" },
        { "c": "🦝", "d": "Racoon" },
        { "c": "🐱", "d": "Cat face" },
        { "c": "🐈", "d": "Cat" },
        { "c": "🐈‍⬛", "d": " Black Cat" },
        { "c": "🦁", "d": "Lion" },
        { "c": "🐯", "d": "Tiger face" },
        { "c": "🐅", "d": "Tiger" },
        { "c": "🐆", "d": "Leopard" },
        { "c": "🐴", "d": "Horse face" },
        { "c": "🐎", "d": "Horse" },
        { "c": "🦄", "d": "Unicorn" },
        { "c": "🦓", "d": "Zebra" },
        { "c": "🦌", "d": "Deer" },
        { "c": "🦬", "d": "Bison" },
        { "c": "🐮", "d": "Cow face" },
        { "c": "🐄", "d": "Cow" },
        { "c": "🐂", "d": "Ox" },
        { "c": "🐃", "d": "Water buffalo" },
        { "c": "🐷", "d": "Pig face" },
        { "c": "🐖", "d": "Pig" },
        { "c": "🐗", "d": "Boar" },
        { "c": "🐽", "d": "Pig nose" },
        { "c": "🐏", "d": "Ram" },
        { "c": "🐑", "d": "Ewe" },
        { "c": "🐐", "d": "Goat" },
        { "c": "🐪", "d": "Camel" },
        { "c": "🐫", "d": "Two hump camel" },
        { "c": "🦙", "d": "Llama" },
        { "c": "🦒", "d": "Giraffe" },
        { "c": "🐘", "d": "Elephant" },
        { "c": "🦣", "d": "Mammoth" },
        { "c": "🦏", "d": "Rhinoceros" },
        { "c": "🦛", "d": "Hippopotamus" },
        { "c": "🐭", "d": "Mouse face" },
        { "c": "🐁", "d": "Mouse" },
        { "c": "🐀", "d": "Rat" },
        { "c": "🐹", "d": "Hamster" },
        { "c": "🐰", "d": "Rabbit face" },
        { "c": "🐇", "d": "Rabbit" },
        { "c": "🐿", "d": "Chipmunk" },
        { "c": "🦫", "d": "Beaver" },
        { "c": "🦔", "d": "Hedgehog" },
        { "c": "🦇", "d": "Bat" },
        { "c": "🐻", "d": "Bear" },
        { "c": "🐻‍❄️", "d": "Polar bear" },
        { "c": "🐨", "d": "Koala" },
        { "c": "🐼", "d": "Panda" },
        { "c": "🦥", "d": "Sloth" },
        { "c": "🦦", "d": "Otter" },
        { "c": "🦨", "d": "Skunk" },
        { "c": "🦘", "d": "Kangaroo" },
        { "c": "🦡", "d": "Badger" },
        { "c": "🐾", "d": "Paw prints" },
        { "c": "🦃", "d": "Turkey" },
        { "c": "🐔", "d": "Chicken" },
        { "c": "🐓", "d": "Rooster" },
        { "c": "🐣", "d": "Hatching" },
        { "c": "🐤", "d": "Baby chick" },
        { "c": "🐥", "d": "Front-facing chick" },
        { "c": "🐦", "d": "Bird" },
        { "c": "🐦‍⬛", "d": "Black bird" },
        { "c": "🐧", "d": "Penguin" },
        { "c": "🕊", "d": "Dove" },
        { "c": "🦅", "d": "Eagle" },
        { "c": "🦆", "d": "Duck" },
        { "c": "🦢", "d": "Swan" },
        { "c": "🦉", "d": "Owl" },
        { "c": "🦤", "d": "Dodo" },
        { "c": "🪶", "d": "Feather" },
        { "c": "🦩", "d": "Flamingo" },
        { "c": "🦜", "d": "Peacock" },
        { "c": "🐸", "d": "Frog" },
        { "c": "🐊", "d": "Crocodile" },
        { "c": "🐢", "d": "Turtle" },
        { "c": "🦎", "d": "Lizard" },
        { "c": "🐍", "d": "Snake" },
        { "c": "🐲", "d": "Dragon face" },
        { "c": "🐉", "d": "Dragon" },
        { "c": "🦕", "d": "Sauropod" },
        { "c": "🦖", "d": "Tyrannosaurus" },
        { "c": "🐳", "d": "Spouting whale" },
        { "c": "🐋", "d": "Whale" },
        { "c": "🐬", "d": "Dolphin" },
        { "c": "🦭", "d": "Seal" },
        { "c": "🐟", "d": "Fish" },
        { "c": "🐠", "d": "Tropical fish" },
        { "c": "🐡", "d": "Blowfish" },
        { "c": "🦈", "d": "Shark" },
        { "c": "🐙", "d": "Octopus" },
        { "c": "🐚", "d": "Spiral shell" },
        { "c": "🐌", "d": "Snail" },
        { "c": "🦋", "d": "Butterfly" },
        { "c": "🐛", "d": "Bug" },
        { "c": "🐜", "d": "Ant" },
        { "c": "🐝", "d": "Honeybee" },
        { "c": "🪲", "d": "Beetle" },
        { "c": "🐞", "d": "Lady Beetle" },
        { "c": "🦗", "d": "Cricket" },
        { "c": "🪳", "d": "Cockroach" },
        { "c": "🕷", "d": "Spider" },
        { "c": "🕸", "d": "Spider web" },
        { "c": "🦂", "d": "Scorpion" },
        { "c": "🦟", "d": "Mosquito" },
        { "c": "🪰", "d": "Fly" },
        { "c": "🪱", "d": "Worm" },
        { "c": "🦠", "d": "Microbe" },
        { "c": "💐", "d": "Bouquet" },
        { "c": "🌸", "d": "Cherry blossom" },
        { "c": "💮", "d": "White flower" },
        { "c": "🏵", "d": "Rosette" },
        { "c": "🌹", "d": "Rose" },
        { "c": "🥀", "d": "Wilted flower" },
        { "c": "🌺", "d": "Hibiscus" },
        { "c": "🌻", "d": "Sunflower" },
        { "c": "🌼", "d": "Blossom" },
        { "c": "🌷", "d": "Tulip" },
        { "c": "🌱", "d": "Seedling" },
        { "c": "🪴", "d": "Potted plant" },
        { "c": "🌲", "d": "Evergreen tree" },
        { "c": "🌳", "d": "Deciduous plant" },
        { "c": "🌴", "d": "Palm tree" },
        { "c": "🌵", "d": "Cactus" },
        { "c": "🌾", "d": "Sheaf of rice" },
        { "c": "🌿", "d": "Herb" },
        { "c": "☘", "d": "Shamrock" },
        { "c": "🍀", "d": "Four leaf clover" },
        { "c": "🍁", "d": "Maple leaf" },
        { "c": "🍂", "d": "Fallen leaf" },
        { "c": "🍃", "d": "Leaf fluttering in wind" },
        { "c": "🪹", "d": "Empty nest" },
        { "c": "🪺", "d": "Nest with eggs" }
    ]
},
{
    "title": "Food and Drinks Emojis",
    "charSet": [
        { "c": "🍇", "d": "Grapes" },
        { "c": "🍈", "d": "Melon" },
        { "c": "🍉", "d": "Water melon" },
        { "c": "🍊", "d": "Tangerine" },
        { "c": "🍋", "d": "Lime" },
        { "c": "🍌", "d": "Banana" },
        { "c": "🍍", "d": "Pineapple" },
        { "c": "🥭", "d": "Mango" },
        { "c": "🍎", "d": "Red apple" },
        { "c": "🍏", "d": "Green apple" },
        { "c": "🍐", "d": "Pear" },
        { "c": "🍑", "d": "Peach" },
        { "c": "🍒", "d": "Cherries" },
        { "c": "🍓", "d": "Strawberries" },
        { "c": "🫐", "d": "Blueberries" },
        { "c": "🥝", "d": "Kiwi fruit" },
        { "c": "🍅", "d": "Tomato" },
        { "c": "🫒", "d": "Olive" },
        { "c": "🥥", "d": "Coconut" },
        { "c": "🥑", "d": "Avocado" },
        { "c": "🍆", "d": "Eggplant" },
        { "c": "🥔", "d": "Potato" },
        { "c": "🥕", "d": "Carrot" },
        { "c": "🌽", "d": "Corn" },
        { "c": "🌶", "d": "Pepper" },
        { "c": "🫑", "d": "Bell pepper" },
        { "c": "🥒", "d": "Cucumber" },
        { "c": "🥬", "d": "Leafy green" },
        { "c": "🥦", "d": "Broccoli" },
        { "c": "🧄", "d": "Garlic" },
        { "c": "🧅", "d": "Onion" },
        { "c": "🍄", "d": "Mushroom" },
        { "c": "🥜", "d": "Peanuts" },
        { "c": "🌰", "d": "Chestnut" },
        { "c": "🍞", "d": "Bread" },
        { "c": "🥐", "d": "Croissant" },
        { "c": "🥖", "d": "Baguette bread" },
        { "c": "🫓", "d": "Flat bread" },
        { "c": "🥨", "d": "Pretzel" },
        { "c": "🥯", "d": "Bagel" },
        { "c": "🥞", "d": "Pancake" },
        { "c": "🧇", "d": "Waffle" },
        { "c": "🧀", "d": "Cheese wedge" },
        { "c": "🍖", "d": "Meat with bone" },
        { "c": "🍗", "d": "Poultry leg" },
        { "c": "🥩", "d": "Cut of meat" },
        { "c": "🥓", "d": "Bacon" },
        { "c": "🍔", "d": "Hamburger" },
        { "c": "🍟", "d": "French fries" },
        { "c": "🍕", "d": "Pizza" },
        { "c": "🌭", "d": "Hot dog" },
        { "c": "🥪", "d": "Sandwich" },
        { "c": "🌮", "d": "Taco" },
        { "c": "🌯", "d": "Burrito" },
        { "c": "🫔", "d": "Tamale" },
        { "c": "🥙", "d": "Stuffed flatbread" },
        { "c": "🧆", "d": "Falafel" },
        { "c": "🥚", "d": "Egg" },
        { "c": "🍳", "d": "Cooking" },
        { "c": "🥘", "d": "Shallow pan of food" },
        { "c": "🍲", "d": "Pot of food" },
        { "c": "🫕", "d": "Fondue" },
        { "c": "🥣", "d": "Bowl with food" },
        { "c": "🥗", "d": "Green salad" },
        { "c": "🍿", "d": "Popcorn" },
        { "c": "🧈", "d": "Butter" },
        { "c": "🧂", "d": "Salt" },
        { "c": "🥫", "d": "Canned food" },
        { "c": "🍱", "d": "Bento box" },
        { "c": "🍘", "d": "RIce cracker" },
        { "c": "🍙", "d": "Rice ball" },
        { "c": "🍚", "d": "Cooked rice" },
        { "c": "🍛", "d": "Curry rice" },
        { "c": "🍜", "d": "Steaming bowl" },
        { "c": "🍝", "d": "Spaghetti" },
        { "c": "🍠", "d": "Roasted sweet potato" },
        { "c": "🍢", "d": "Oden" },
        { "c": "🍣", "d": "Sushi" },
        { "c": "🍤", "d": "Fried shrimp" },
        { "c": "🍥", "d": "Fish cake with swiri" },
        { "c": "🥮", "d": "Moon cake" },
        { "c": "🍡", "d": "Dango" },
        { "c": "🥟", "d": "Dumpling" },
        { "c": "🥠", "d": "Fortune cookie" },
        { "c": "🥡", "d": "Take out box" },
        { "c": "🦀", "d": "Crab" },
        { "c": "🦞", "d": "Lobster" },
        { "c": "🦐", "d": "Shrimp" },
        { "c": "🦑", "d": "Squid" },
        { "c": "🦪", "d": "Oyster" },
        { "c": "🍨", "d": "Ice cream" },
        { "c": "🍧", "d": "Shaved ice cream" },
        { "c": "🍦", "d": "Soft ice cream" },
        { "c": "🍩", "d": "Doughnut" },
        { "c": "🍪", "d": "Cookie" },
        { "c": "🎂", "d": "Birthday cake" },
        { "c": "🍰", "d": "Short cake" },
        { "c": "🧁", "d": "Cup cake" },
        { "c": "🥧", "d": "Pie" },
        { "c": "🍫", "d": "Chocolate" },
        { "c": "🍬", "d": "Candy" },
        { "c": "🍭", "d": "Lollipop" },
        { "c": "🍮", "d": "Custard" },
        { "c": "🍯", "d": "Honey pot" },
        { "c": "🍼", "d": "Baby bottle" },
        { "c": "🥛", "d": "Glass of milk" },
        { "c": "☕", "d": "Hot beverage" },
        { "c": "🫖", "d": "Teapot" },
        { "c": "🍵", "d": "Teacup without handle" },
        { "c": "🍶", "d": "Sake" },
        { "c": "🍾", "d": "Bottle with poppin cork" },
        { "c": "🍷", "d": "Wine glass" },
        { "c": "🍸", "d": "Cocktail glass" },
        { "c": "🍹", "d": "Tropical drink" },
        { "c": "🍺", "d": "Beer mug" },
        { "c": "🍻", "d": "Clinking beer mug" },
        { "c": "🥂", "d": "Clinking glasses" },
        { "c": "🥃", "d": "Tumbler glass" },
        { "c": "🥤", "d": "Cup with strawberry" },
        { "c": "🧋", "d": "Bubble tea" },
        { "c": "🧃", "d": "Beverage box" },
        { "c": "🧉", "d": "Mate drink" },
        { "c": "🧊", "d": "Ice" },
        { "c": "🥢", "d": "Chopsticks" },
        { "c": "🍽", "d": "Fork and knife with plate" },
        { "c": "🍴", "d": "Fork and knife" },
        { "c": "🥄", "d": "Spoon" },
        { "c": "🔪", "d": "Kitchen knife" },
        { "c": "🧋", "d": "Jar" },
        { "c": "🏺", "d": "Amphora" }
    ]
},
{
    "title": "Travel and Places Emojis",
    "charSet": [
        { "c": "🌍", "d": "Globe showing Africa and Europe" },
        { "c": "🌎", "d": "Globe showing Americas" },
        { "c": "🌏", "d": "Globe showing Asia and Australia" },
        { "c": "🌐", "d": "Globe with meridians" },
        { "c": "🗺", "d": "World map" },
        { "c": "🧭", "d": "Compass" },
        { "c": "⛰", "d": "Mountain" },
        { "c": "🏔", "d": "Snowcap mountain" },
        { "c": "🌋", "d": "Volcanic mountain" },
        { "c": "🗻", "d": "Fuji mountain" },
        { "c": "🏕", "d": "Camping" },
        { "c": "🏖", "d": "Beach with umbrella" },
        { "c": "🏜", "d": "Desert" },
        { "c": "🏝", "d": "Desertified island" },
        { "c": "🏞", "d": "National park" },
        { "c": "🏟", "d": "Stadium" },
        { "c": "🏛", "d": "Classical building" },
        { "c": "🏗", "d": "Building construction" },
        { "c": "🧱", "d": "Brick" },
        { "c": "🪨", "d": "Rock" },
        { "c": "🪵", "d": "Wood" },
        { "c": "🛖", "d": "Hut" },
        { "c": "🏘", "d": "Houses" },
        { "c": "🏚", "d": "Derelict house" },
        { "c": "🏠", "d": "House" },
        { "c": "🏡", "d": "House with garden" },
        { "c": "🏢", "d": "Office building" },
        { "c": "🏣", "d": "Japanese office" },
        { "c": "🏤", "d": "Post office" },
        { "c": "🏥", "d": "Hospital" },
        { "c": "🏦", "d": "Bank" },
        { "c": "🏨", "d": "Hotel" },
        { "c": "🏩", "d": "Love hotel" },
        { "c": "🏪", "d": "Convenience store" },
        { "c": "🏫", "d": "School" },
        { "c": "🏬", "d": "Department" },
        { "c": "🏭", "d": "Factory" },
        { "c": "🏯", "d": "Japanese castle" },
        { "c": "🏰", "d": "Castle" },
        { "c": "💒", "d": "Wedding house" },
        { "c": "🗼", "d": "Tokyo tower" },
        { "c": "🗽", "d": "Statue of liberty" },
        { "c": "⛪", "d": "Church" },
        { "c": "🕌", "d": "Mosque" },
        { "c": "🛕", "d": "Hindu temple" },
        { "c": "🕍", "d": "Synagogue" },
        { "c": "⛩", "d": "Shinto shrine" },
        { "c": "🕋", "d": "Kaaba" },
        { "c": "⛲", "d": "Fountain" },
        { "c": "⛺", "d": "Tent" },
        { "c": "🌁", "d": "Foggy" },
        { "c": "🌃", "d": "Night with starrs" },
        { "c": "🏙", "d": "Citscape" },
        { "c": "🌅", "d": "Sunrise" },
        { "c": "🌄", "d": "Sunrise over mountains" },
        { "c": "🌆", "d": "Cityscape at dusk" },
        { "c": "🌇", "d": "Sunset" },
        { "c": "🌉", "d": "Bridge at night" },
        { "c": "♨", "d": "Hot springs" },
        { "c": "🎠", "d": "Carousel horse" },
        { "c": "🎡", "d": "Ferris wheel" },
        { "c": "🎢", "d": "Roller coaster" },
        { "c": "💈", "d": "Barber poll" },
        { "c": "🎪", "d": "Circus tent" }
    ]
},
{
    "title": "Transport Emojis",
    "charSet": [
        { "c": "🚂", "d": "Locomotive" },
        { "c": "🚃", "d": "Railway car" },
        { "c": "🚄", "d": "High speed train" },
        { "c": "🚅", "d": "Bullet train" },
        { "c": "🚆", "d": "Train" },
        { "c": "🚇", "d": "Metro" },
        { "c": "🚈", "d": "Light rail" },
        { "c": "🚉", "d": "Station" },
        { "c": "🚊", "d": "Tram" },
        { "c": "🚝", "d": "Monorail" },
        { "c": "🚞", "d": "Mountain railway" },
        { "c": "🚋", "d": "Tram car" },
        { "c": "🚌", "d": "us" },
        { "c": "🚍", "d": "Oncoming bus" },
        { "c": "🚎", "d": "Trolley bus" },
        { "c": "🚐", "d": "Minibus" },
        { "c": "🚑", "d": "Ambulance" },
        { "c": "🚒", "d": "Fire engine" },
        { "c": "🚓", "d": "Police car" },
        { "c": "🚔", "d": "Oncoming police car" },
        { "c": "🚕", "d": "Taxi" },
        { "c": "🚖", "d": "Oncoming taxi" },
        { "c": "🚗", "d": "Automobile" },
        { "c": "🚘", "d": "Oncoming automobile" },
        { "c": "🚙", "d": "Sport utility vehicle" },
        { "c": "🛻", "d": "Pickup truck" },
        { "c": "🚚", "d": "Delivery truck" },
        { "c": "🚛", "d": "Articulated lorry" },
        { "c": "🚜", "d": "Tractor" },
        { "c": "🏎", "d": "Racing car" },
        { "c": "🏍", "d": "Motorcycle" },
        { "c": "🛵", "d": "Scooter" },
        { "c": "🦽", "d": "Manual wheelchair" },
        { "c": "🦼", "d": "Motorized wheelchair" }
    ]
},
{
    "title": "Time Emojis",
    "charSet": [
        { "c": "⌛", "d": "Hourglass done" },
        { "c": "⏳", "d": "Hourglass starting" },
        { "c": "⌚", "d": "Watch" },
        { "c": "⏰", "d": "Alarm" },
        { "c": "⏱", "d": "Stopwatch" },
        { "c": "⏲", "d": "Timer clock" },
        { "c": "🕰", "d": "Mantelpiece clock" },
        { "c": "🕛", "d": "Twelve O'clock" },
        { "c": "🕧", "d": "Twelve-thirty" },
        { "c": "🕐", "d": "One O'clock" },
        { "c": "🕜", "d": "One-thirty" },
        { "c": "🕑", "d": "Two O'clock" },
        { "c": "🕝", "d": "Two-thirty" },
        { "c": "🕒", "d": "Three O'clock" },
        { "c": "🕞", "d": "Three-thirty" },
        { "c": "🕓", "d": "Four O'clock" },
        { "c": "🕟", "d": "Four-thirty" },
        { "c": "🕔", "d": "Five O'clock" },
        { "c": "🕠", "d": "Five-thirty" },
        { "c": "🕕", "d": "Six O'clock" },
        { "c": "🕡", "d": "Six-thirty" },
        { "c": "🕖", "d": "Seven O'clock" },
        { "c": "🕢", "d": "Seven-thirty" },
        { "c": "🕗", "d": "Eight O'clock" },
        { "c": "🕣", "d": "Eight-thirty" },
        { "c": "🕘", "d": "Nine O'clock" },
        { "c": "🕤", "d": "Nine-thirty" },
        { "c": "🕙", "d": "Ten O'clock" },
        { "c": "🕥", "d": "Ten-thirty" },
        { "c": "🕚", "d": "Eleven O'clock" },
        { "c": "🕦", "d": "Eleven-thirty" }
    ]
},
{
    "title": "Sky and Weather Emojis",
    "charSet": [
        { "c": "🌑", "d": "New moon" },
        { "c": "🌒", "d": "Waxing crescent moon" },
        { "c": "🌓", "d": "First quarter moon" },
        { "c": "🌔", "d": "Waxing gibbous moon" },
        { "c": "🌕", "d": "Full moon" },
        { "c": "🌖", "d": "Waning gibbous moon" },
        { "c": "🌗", "d": "Last quarter moon" },
        { "c": "🌘", "d": "Waning crescent moon" },
        { "c": "🌙", "d": "Crescent moon" },
        { "c": "🌚", "d": "New moon face" },
        { "c": "🌛", "d": "First quarter moon face" },
        { "c": "🌜", "d": "Last quartermoon face" },
        { "c": "🌡", "d": "Thermometer" },
        { "c": "☀", "d": "Sun" },
        { "c": "🌝", "d": "Full moon face" },
        { "c": "🌞", "d": "Sun with face" },
        { "c": "🪐", "d": "Ringed planet" },
        { "c": "⭐", "d": "Star" },
        { "c": "🌟", "d": "Glowing star" },
        { "c": "🌠", "d": "Shooting star" },
        { "c": "🌌", "d": "Milky way" },
        { "c": "☁", "d": "Cloud" },
        { "c": "⛅", "d": "Sun behind cloud" },
        { "c": "⛈", "d": "Cloud with lighting and rain" },
        { "c": "🌤", "d": "Sun behind small cloud" },
        { "c": "🌥", "d": "Sun behind large cloud" },
        { "c": "🌦", "d": "Sun behind rain cloud" },
        { "c": "🌧", "d": "Cloud with rain" },
        { "c": "🌨", "d": "Cloud with snow" },
        { "c": "🌩", "d": "Cloud with lighting" },
        { "c": "🌪", "d": "Tornado" },
        { "c": "🌫", "d": "Fog" },
        { "c": "🌬", "d": "Wind face" },
        { "c": "🌀", "d": "Cyclone" },
        { "c": "🌈", "d": "Rainbow" },
        { "c": "🌂", "d": "Closed umbrella" },
        { "c": "☂", "d": "Umbrella" },
        { "c": "☔", "d": "Umbrella with raindrops" },
        { "c": "⛱", "d": "Umbrella on ground" },
        { "c": "⚡", "d": "High voltage" },
        { "c": "❄", "d": "Snowflake" },
        { "c": "☃", "d": "Snowman" },
        { "c": "⛄", "d": "Snowman without snow" },
        { "c": "☄", "d": "Comet" },
        { "c": "🔥", "d": "Fire" },
        { "c": "💧", "d": "Droplet" },
        { "c": "🌊", "d": "Water wave" }
    ]
},
{
    "title": "Activity Emojis",
    "charSet": [
        { "c": "🎃", "d": "Jack-o-lantern" },
        { "c": "🎄", "d": "Christmas tree" },
        { "c": "🎆", "d": "Fireworks" },
        { "c": "🎇", "d": "Sparkler" },
        { "c": "🧨", "d": "Firecracker" },
        { "c": "✨", "d": "Sparkles" },
        { "c": "🎈", "d": "Baloon" },
        { "c": "🎉", "d": "Party popper" },
        { "c": "🎊", "d": "Confetti ball" },
        { "c": "🎋", "d": "Tanabata tree" },
        { "c": "🎍", "d": "Pine decoration" },
        { "c": "🎎", "d": "Japanese dolls" },
        { "c": "🎏", "d": "Carp streamer" },
        { "c": "🎑", "d": "Moon viewing ceremony" },
        { "c": "🧧", "d": "Red envelope" },
        { "c": "🎀", "d": "Ribbon" },
        { "c": "🎁", "d": "Wrapped gift" },
        { "c": "🎗", "d": "Reminder ribbon" },
        { "c": "🎟", "d": "Admission ticket" },
        { "c": "🎫", "d": "Ticket" }
    ]
},
{
    "title": "Award Medals Emojis",
    "charSet": [
        { "c": "🎖", "d": "Military medal" },
        { "c": "🏆", "d": "Trophy" },
        { "c": "🏅", "d": "Sports medal" },
        { "c": "🥇", "d": "Gold medal - first position" },
        { "c": "🥈", "d": "Silver medal - second position" },
        { "c": "🥉", "d": "Bronze medal - third position" }
    ]
},
{
    "title": "Sport Emojis",
    "charSet": [
        { "c": "⚽", "d": "Soccer ball" },
        { "c": "⚾", "d": "Baseball" },
        { "c": "🥎", "d": "Softball" },
        { "c": "🏀", "d": "Basketball" },
        { "c": "🏐", "d": "Volleyball" },
        { "c": "🏈", "d": "American football" },
        { "c": "🏉", "d": "Rugby" },
        { "c": "🎾", "d": "Tennis" },
        { "c": "🥏", "d": "Flying disk" },
        { "c": "🎳", "d": "Bowling" },
        { "c": "🏏", "d": "Cricket" },
        { "c": "🏑", "d": "Field hockey" },
        { "c": "🏒", "d": "Ice hockey" },
        { "c": "🥍", "d": "Lacrosse" },
        { "c": "🏓", "d": "Ping pong" },
        { "c": "🏸", "d": "Badminton" },
        { "c": "🥊", "d": "Boxing glove" },
        { "c": "🥋", "d": "Martial arts uniform" },
        { "c": "🥅", "d": "Goal net" },
        { "c": "⛳", "d": "Flag in a hole" },
        { "c": "⛸", "d": "Ice skate" },
        { "c": "🎣", "d": "Fishing pole" },
        { "c": "🤿", "d": "Diving mask" },
        { "c": "🎽", "d": "Running shirt" },
        { "c": "🎿", "d": "Skis" },
        { "c": "🛷", "d": "Sled" },
        { "c": "🥌", "d": "Curling stone" }
    ]
},
{
    "title": "Games Emojis",
    "charSet": [
        { "c": "🎯", "d": "Bullseye" },
        { "c": "🪀", "d": "Yo-yo" },
        { "c": "🪁", "d": "Kite" },
        { "c": "🎱", "d": "8 ball" },
        { "c": "🔮", "d": "Crystal ball" },
        { "c": "🪄", "d": "Magic wand" },
        { "c": "🧿", "d": "Nazar amulet" },
        { "c": "🪬", "d": "Hamsa" },
        { "c": "🎮", "d": "Video game pad" },
        { "c": "🕹", "d": "Joystick" },
        { "c": "🎰", "d": "Slot machine" },
        { "c": "🎲", "d": "Game die" },
        { "c": "🧩", "d": "Puzzle piece" },
        { "c": "🧸", "d": "Teddy bear" },
        { "c": "🪅", "d": "Piñata" },
        { "c": "🪆", "d": "Nesting doll" },
        { "c": "♠", "d": "Spade suit" },
        { "c": "♥", "d": "Heart suit" },
        { "c": "♣", "d": "Club suit" },
        { "c": "♟", "d": "Chess pawn" },
        { "c": "🃏", "d": "Joker" },
        { "c": "🀄", "d": "Mahjong red dragon" },
        { "c": "🎴", "d": "Flower playing cards" }
    ]
},
{
    "title": "Arts and Crafts Emojis",
    "charSet": [
        { "c": "🎭", "d": "Performing arts" },
        { "c": "🖼", "d": "Framed picture" },
        { "c": "🎨", "d": "Artist palette" },
        { "c": "🧵", "d": "Thread" },
        { "c": "🪡", "d": "Sewing needle with thread" },
        { "c": "🧶", "d": "Yarn" },
        { "c": "🪢", "d": "Knot" }
    ]
},
{
    "title": "Clothing Objects Emojis",
    "charSet": [
        { "c": "👓", "d": "Glasses" },
        { "c": "🕶", "d": "Sunglasses" },
        { "c": "🥽", "d": "Goggles" },
        { "c": "🥼", "d": "Lab coat" },
        { "c": "🦺", "d": "Safety vest" },
        { "c": "👔", "d": "Necktie" },
        { "c": "👕", "d": "T-shirt" },
        { "c": "👖", "d": "Jeans" },
        { "c": "🧣", "d": "Scarf" },
        { "c": "🧤", "d": "Gloves" },
        { "c": "🧥", "d": "Coat" },
        { "c": "🧦", "d": "Socks" },
        { "c": "👗", "d": "Dress" },
        { "c": "👘", "d": "Kimono" },
        { "c": "🥻", "d": "Sari" },
        { "c": "🩱", "d": "One piece suit" },
        { "c": "🩲", "d": "Briefs" },
        { "c": "🩳", "d": "Shorts" },
        { "c": "👙", "d": "Bikini" },
        { "c": "👚", "d": "Woman's shirt" },
        { "c": "👛", "d": "Purse" },
        { "c": "👜", "d": "Handbag" },
        { "c": "👝", "d": "Clutch bag" },
        { "c": "🛍", "d": "Shopping bags" },
        { "c": "🎒", "d": "Backpack" },
        { "c": "🩴", "d": "Thong sandals" },
        { "c": "👞", "d": "Man's shoe" },
        { "c": "👟", "d": "Running shoe" },
        { "c": "🥾", "d": "Hiking boot" },
        { "c": "🥿", "d": "Flat shoe" },
        { "c": "👠", "d": "High-heeled shoe" },
        { "c": "👡", "d": "Woman's sandal" },
        { "c": "🩰", "d": "Ballet shoes" },
        { "c": "👢", "d": "Woman's boot" },
        { "c": "👑", "d": "Crown" },
        { "c": "👒", "d": "Woman's hat" },
        { "c": "🎩", "d": "Top hat" },
        { "c": "🎓", "d": "Graduation cap" },
        { "c": "🧢", "d": "Billed cap" },
        { "c": "🪖", "d": "Military helmet" },
        { "c": "⛑", "d": "Rescue worker's helmet" },
        { "c": "📿", "d": "Prayer beads" },
        { "c": "💄", "d": "Lipstick" },
        { "c": "💍", "d": "Ring" },
        { "c": "💎", "d": "Gemstone" }
    ]
},
{
    "title": "Sound Emojis",
    "charSet": [
        { "c": "🔇", "d": "Muted speaker" },
        { "c": "🔈", "d": "Low volume speaker" },
        { "c": "🔉", "d": "Mid volume speaker" },
        { "c": "🔊", "d": "High volume speaker" },
        { "c": "📢", "d": "Loudspeaker" },
        { "c": "📣", "d": "Megaphone" },
        { "c": "📯", "d": "Postal horn" },
        { "c": "🔔", "d": "Bell" },
        { "c": "🔕", "d": "Bell with slash" },
        { "c": "🎼", "d": "Musical score" },
        { "c": "🎵", "d": "Musical note" },
        { "c": "🎶", "d": "Musical notes" },
        { "c": "🎙", "d": "Studio microphone" },
        { "c": "🎚", "d": "Level slider" },
        { "c": "🎛", "d": "Control knobs" },
        { "c": "🎤", "d": "Microphone" },
        { "c": "🎧", "d": "Headphone" },
        { "c": "📻", "d": "Radio" }
    ]
},
{
    "title": "Musical Instrument Emojis",
    "charSet": [
        { "c": "🎷", "d": "Saxophone" },
        { "c": "🪗", "d": "Accordion" },
        { "c": "🎸", "d": "Guitar" },
        { "c": "🎹", "d": "Musical keyboard" },
        { "c": "🎺", "d": "Trumpet" },
        { "c": "🎻", "d": "Violin" },
        { "c": "🪕", "d": "Banjo" },
        { "c": "🥁", "d": "Drum" },
        { "c": "🪘", "d": "Long drum" }
    ]
},
{
    "title": "Phone Emojis",
    "charSet": [
        { "c": "📱", "d": "Mobile phone" },
        { "c": "📲", "d": "Mobile phone with arrow" },
        { "c": "☎", "d": "Telephone" },
        { "c": "📞", "d": "Telephone receiver" },
        { "c": "📟", "d": "Pager" },
        { "c": "📠", "d": "Fax machine" }
    ]
},
{
    "title": "Computer Emojis",
    "charSet": [
        { "c": "🔋", "d": "Full battery" },
        { "c": "🪫", "d": "Low battery" },
        { "c": "🔌", "d": "Electric plug" },
        { "c": "💻", "d": "Laptop" },
        { "c": "🖥", "d": "Desktop computer" },
        { "c": "🖨", "d": "Printer" },
        { "c": "⌨", "d": "Keyboard" },
        { "c": "🖱", "d": "Mouse" },
        { "c": "🖲", "d": "Trackball" },
        { "c": "💽", "d": "Computer disk" },
        { "c": "💾", "d": "Floppy disk" },
        { "c": "💿", "d": "Optical disk" },
        { "c": "📀", "d": "DVD" },
        { "c": "🧮", "d": "Abacus" }
    ]
},
{
    "title": "Light and Video Emojis",
    "charSet": [
        { "c": "🎥", "d": "Movie camera" },
        { "c": "🎞", "d": "Film frames" },
        { "c": "📽", "d": "Film Projector" },
        { "c": "🎬", "d": "Clapper board" },
        { "c": "📺", "d": "Television" },
        { "c": "📷", "d": "Camera" },
        { "c": "📸", "d": "Camera with flash" },
        { "c": "📹", "d": "Video camera" },
        { "c": "📼", "d": "Video cassette" },
        { "c": "🔍", "d": "Magnifying glass tilted left" },
        { "c": "🔎", "d": "Magnifying glass tilted right" },
        { "c": "🕯", "d": "Candle" },
        { "c": "💡", "d": "Light bulb" },
        { "c": "🔦", "d": "Flashlight" },
        { "c": "🏮", "d": "Red pepper lantern" },
        { "c": "🪔", "d": "Diya lamp" }
    ]
},
{
    "title": "Book and Paper Emojis",
    "charSet": [
        { "c": "📔", "d": "Notebook with decorative cover" },
        { "c": "📕", "d": "Closed notebook" },
        { "c": "📖", "d": "Opened notebook" },
        { "c": "📗", "d": "Green book" },
        { "c": "📘", "d": "Blue book" },
        { "c": "📙", "d": "Orange book" },
        { "c": "📚", "d": "Orange books" },
        { "c": "📓", "d": "Notebook" },
        { "c": "📒", "d": "Ledger" },
        { "c": "📃", "d": "Page with curl" },
        { "c": "📜", "d": "Scroll" },
        { "c": "📄", "d": "Page facing up" },
        { "c": "📰", "d": "Newspaper" },
        { "c": "🗞", "d": "Rolled-up newspaper" },
        { "c": "📑", "d": "Bookmark tabs" },
        { "c": "🔖", "d": "Bookmark" },
        { "c": "🏷", "d": "Label" },
        { "c": "💰", "d": "Money bag" },
        { "c": "🪙", "d": "Coin" },
        { "c": "💴", "d": "Yen banknote" },
        { "c": "💵", "d": "Dollar banknote" },
        { "c": "💶", "d": "Euro banknote" },
        { "c": "💷", "d": "Pound banknote" },
        { "c": "💸", "d": "Money with wings" },
        { "c": "💳", "d": "Credit card" },
        { "c": "🧾", "d": "Receipt" },
        { "c": "💹", "d": "Chart increase woth Yen" }
    ]
},
{
    "title": "Mail Emojis",
    "charSet": [
        { "c": "✉", "d": "Envelope" },
        { "c": "📧", "d": "e-mail" },
        { "c": "📩", "d": "Envelope with arrow" },
        { "c": "📤", "d": "Outbox tray" },
        { "c": "📥", "d": "Inbox tray" },
        { "c": "📦", "d": "Package" },
        { "c": "📫", "d": "Closed mailbox with raised flag" },
        { "c": "📪", "d": "Closed mailbox with lowered flag" },
        { "c": "📬", "d": "Open mailbox with raised flag" },
        { "c": "📭", "d": "Open mailbox with lowered flag" },
        { "c": "📮", "d": "Postbox" },
        { "c": "🗳", "d": "Ballot box with ballot" }
    ]
},
{
    "title": "Writing Emojis",
    "charSet": [
        { "c": "✏", "d": "Pencil" },
        { "c": "✒", "d": "Black nib" },
        { "c": "🖋", "d": "Fountain pen" },
        { "c": "🖊", "d": "Pen" },
        { "c": "🖌", "d": "Paintbrush" },
        { "c": "🖍", "d": "Crayon" },
        { "c": "📝", "d": "Memo" }
    ]
},
{
    "title": "Office Emojis",
    "charSet": [
        { "c": "💼", "d": "Briefcase" },
        { "c": "📁", "d": "File folder" },
        { "c": "📂", "d": "Open the folder" },
        { "c": "🗂", "d": "Card index dividers" },
        { "c": "📅", "d": "Calender" },
        { "c": "📆", "d": "Tear off calender" },
        { "c": "📇", "d": "Card index" },
        { "c": "📈", "d": "Increasing chart" },
        { "c": "📉", "d": "Decreasing chart" },
        { "c": "📊", "d": "Bar chart" },
        { "c": "📋", "d": "Clipboard" },
        { "c": "📌", "d": "Pushpin" },
        { "c": "📍", "d": "Round pushpin" },
        { "c": "📎", "d": "Paperclip" },
        { "c": "🖇", "d": "Linked paperclips" },
        { "c": "📏", "d": "Straight ruler" },
        { "c": "📐", "d": "Triangular ruler" },
        { "c": "✂", "d": "Scissors" },
        { "c": "🗃", "d": "Card file box" },
        { "c": "🗄", "d": "File cabinet" },
        { "c": "🗑", "d": "Waste basket" }
    ]
},
{
    "title": "Lock Emojis",
    "charSet": [
        { "c": "🔒", "d": "Locked" },
        { "c": "🔓", "d": "Unlocked" },
        { "c": "🔏", "d": "Locked with pen" },
        { "c": "🔐", "d": "Locked with key" },
        { "c": "🔑", "d": "Key" },
        { "c": "🗝", "d": "Old key" }
    ]
},
{
    "title": "Tools Emojis",
    "charSet": [
        { "c": "🔨", "d": "Hammer" },
        { "c": "🪓", "d": "Axe" },
        { "c": "⛏", "d": "Pick" },
        { "c": "⚒", "d": "Hammer and pick" },
        { "c": "🛠", "d": "Hammer and wrench" },
        { "c": "🗡", "d": "Sword" },
        { "c": "⚔", "d": "Crossed swords" },
        { "c": "🔫", "d": "Water gun" },
        { "c": "🪃", "d": "Boomerang" },
        { "c": "🏹", "d": "Bow and arrow" },
        { "c": "🛡", "d": "Shield" },
        { "c": "🪚", "d": "Carpentry saw" },
        { "c": "🔧", "d": "Wrench" },
        { "c": "🪛", "d": "Screwdriver" },
        { "c": "🔩", "d": "Bolt and nut" },
        { "c": "⚙", "d": "Wheel" },
        { "c": "🗜", "d": "Clamp" },
        { "c": "⚖", "d": "Balance scale" },
        { "c": "🦯", "d": "White cane" },
        { "c": "🔗", "d": "Link" },
        { "c": "⛓", "d": "Chains" },
        { "c": "🪝", "d": "Hook" },
        { "c": "🧰", "d": "Toolbox" },
        { "c": "🧲", "d": "Magnet" },
        { "c": "🪜", "d": "Ladder" }
    ]
},
{
    "title": "Science Emojis",
    "charSet": [
        { "c": "⚗", "d": "Alembic" },
        { "c": "🧪", "d": "Test tube" },
        { "c": "🧫", "d": "Petri dish" },
        { "c": "🧬", "d": "DNA" },
        { "c": "🔬", "d": "Microscope" },
        { "c": "🔭", "d": "Telescope" },
        { "c": "📡", "d": "Satelite antenna" }
    ]
},
{
    "title": "Medical Emojis",
    "charSet": [
        { "c": "💉", "d": "Syringe" },
        { "c": "🩸", "d": "A droplet of blood" },
        { "c": "💊", "d": "Pill" },
        { "c": "🩹", "d": "Adhesive bandage" },
        { "c": "🩼", "d": "Crutch" },
        { "c": "🩺", "d": "Stethoscope" },
        { "c": "🩻", "d": "X-ray" }
    ]
},
{
    "title": "Household Emojis",
    "charSet": [
        { "c": "🚪", "d": "Door" },
        { "c": "🛗", "d": "Elevator" },
        { "c": "🪞", "d": "Mirror" },
        { "c": "🪟", "d": "Window" },
        { "c": "🛏", "d": "Bed" },
        { "c": "🛋", "d": "Couch and lamp" },
        { "c": "🪑", "d": "Chair" },
        { "c": "🚽", "d": "Toilet" },
        { "c": "🪠", "d": "Plunger" },
        { "c": "🚿", "d": "Shower" },
        { "c": "🛁", "d": "Bathtub" },
        { "c": "🪤", "d": "Mouse trap" },
        { "c": "🪒", "d": "Razor" },
        { "c": "🧴", "d": "Lotion bottle" },
        { "c": "🧷", "d": "Safety pin" },
        { "c": "🧹", "d": "Broom" },
        { "c": "🧺", "d": "Basket" },
        { "c": "🧻", "d": "Roll of paper" },
        { "c": "🪣", "d": "Bucket" },
        { "c": "🧼", "d": "Soap" },
        { "c": "🫧", "d": "Bubbles" },
        { "c": "🪥", "d": "Toothbrush" },
        { "c": "🧽", "d": "Sponge" },
        { "c": "🧯", "d": "Fire extinguisher" },
        { "c": "🛒", "d": "Shopping cart" }
    ]
},
{
    "title": "Other Objects Emojis",
    "charSet": [
        { "c": "🚬", "d": "Cigarette" },
        { "c": "⚰", "d": "Casket" },
        { "c": "🪦", "d": "Headstone" },
        { "c": "⚱", "d": "Funeral urn" },
        { "c": "🗿", "d": "Moai" },
        { "c": "🪧", "d": "Placard" },
        { "c": "🪪", "d": "ID Card" }
    ]
},
{
    "title": "Symbols",
    "charSet": [
        { "c": "🏧", "d": "ATM Sign" },
        { "c": "🚮", "d": "Litter in bin" },
        { "c": "🚰", "d": "Portable water" },
        { "c": "♿", "d": "Wheelchair symbol" },
        { "c": "🚹", "d": "Men's room symbol" },
        { "c": "🚺", "d": "Women's room symbol" },
        { "c": "🚻", "d": "Restroom symbol" },
        { "c": "🚼", "d": "Baby symbol" },
        { "c": "🚾", "d": "Water closet" },
        { "c": "🛂", "d": "Passport control" },
        { "c": "🛃", "d": "Customs" },
        { "c": "🛄", "d": "Baggage claim" },
        { "c": "🛅", "d": "Left laugage" }
    ]
},
{
    "title": "Warning Emojis",
    "charSet": [
        { "c": "⚠", "d": "Warning" },
        { "c": "🚸", "d": "Children crossing" },
        { "c": "⛔", "d": "No entry" },
        { "c": "🚫", "d": "Prohibited" },
        { "c": "🚳", "d": "No bicycles" },
        { "c": "🚭", "d": "No smoking" },
        { "c": "🚯", "d": "No littering" },
        { "c": "🚱", "d": "Non-portable water" },
        { "c": "🚷", "d": "No pedestrians" },
        { "c": "📵", "d": "No mobile phones" },
        { "c": "🔞", "d": "No one under 18" },
        { "c": "☢", "d": "Radioactive" },
        { "c": "☣", "d": "Biohazard" }
    ]
},
{
    "title": "Arrow Emojis",
    "charSet": [
        { "c": "⬆", "d": "Up Arrow" },
        { "c": "↗", "d": "Up-right arrow" },
        { "c": "➡", "d": "Right arrow" },
        { "c": "↘", "d": "Down-right arrow" },
        { "c": "⬇", "d": "Down arrow" },
        { "c": "↙", "d": "Down-left arrow" },
        { "c": "⬅", "d": "Left arrow" },
        { "c": "↖", "d": "Up-left arrow" },
        { "c": "↕", "d": "Up-down arrow" },
        { "c": "↔", "d": "Left arrow" },
        { "c": "↩", "d": "Right arrow curving left" },
        { "c": "↪", "d": "Left arrow curving right" },
        { "c": "⤴", "d": "Right arrow curving up" },
        { "c": "⤵", "d": "Right arrow curving down" },
        { "c": "🔃", "d": "Clockwise vertical arrow" },
        { "c": "🔄", "d": "Counterclockwise arrows button" },
        { "c": "🔙", "d": "Back arrow" },
        { "c": "🔚", "d": "End arrow" },
        { "c": "🔛", "d": "On arrow" },
        { "c": "🔜", "d": "Soon arrow" },
        { "c": "🔝", "d": "Top arrow" }
    ]
},
{
    "title": "Religion",
    "charSet": [
        { "c": "🛐", "d": "Place of worship" },
        { "c": "⚛", "d": "Atom symbol" },
        { "c": "🕉", "d": "OM" },
        { "c": "✡", "d": "Star of David" },
        { "c": "☸", "d": "Wheel of Dharma" },
        { "c": "☯", "d": "Yin yang" },
        { "c": "✝", "d": "Latin cross" },
        { "c": "☦", "d": "Orthodox cross" },
        { "c": "☪", "d": "Star and cresent moon" },
        { "c": "☮", "d": "Peace" },
        { "c": "🕎", "d": "Menorah" },
        { "c": "🔯", "d": "Six-pointed star" }
    ]
},
{
    "title": "Zodiac",
    "charSet": [
        { "c": "♈", "d": "Aries" },
        { "c": "♉", "d": "Taurus" },
        { "c": "♊", "d": "Gemini" },
        { "c": "♋", "d": "Cancer" },
        { "c": "♌", "d": "Leo" },
        { "c": "♍", "d": "Virgo" },
        { "c": "♎", "d": "Libra" },
        { "c": "♏", "d": "Scorpio" },
        { "c": "♐", "d": "Sagittarius" },
        { "c": "♑", "d": "Capricon" },
        { "c": "♒", "d": "Acquarius" },
        { "c": "♓", "d": "Pisces" },
        { "c": "⛎", "d": "Ophiucus" }
    ]
},
{
    "title": "AV Symbols",
    "charSet": [
        { "c": "🔀", "d": "Shuffle tracks" },
        { "c": "🔁", "d": "Repeat all" },
        { "c": "🔂", "d": "Repeat one" },
        { "c": "▶", "d": "Play" },
        { "c": "⏸", "d": "Pause" },
        { "c": "⏩", "d": "Fast-forward" },
        { "c": "⏭", "d": "Next track" },
        { "c": "⏯", "d": "Play or pause" },
        { "c": "◀", "d": "Reverse" },
        { "c": "⏪", "d": "Fast-reverse" },
        { "c": "⏮", "d": "Previous track" },
        { "c": "🔼", "d": "Upwards" },
        { "c": "⏫", "d": "Fast-up" },
        { "c": "🔽", "d": "Downwards" },
        { "c": "⏬", "d": "Fast down" },
        { "c": "⏹", "d": "Stop" },
        { "c": "⏺", "d": "Record" },
        { "c": "⏏", "d": "Eject" },
        { "c": "🎦", "d": "Cinema" },
        { "c": "🔅", "d": "Dim" },
        { "c": "🔆", "d": "Bright" },
        { "c": "📶", "d": "Network antenna bars" },
        { "c": "📳", "d": "Vibration mode" },
        { "c": "📴", "d": "Mobile phone off" }
    ]
},
{
    "title": "Gender",
    "charSet": [
        { "c": "♀", "d": "Female" },
        { "c": "♂", "d": "Male" },
        { "c": "⚧", "d": "Transgender" }
    ]
},
{
    "title": "Math Symbols",
    "charSet": [
        { "c": "✖", "d": "Times" },
        { "c": "➕", "d": "Plus" },
        { "c": "➖", "d": "Minus" },
        { "c": "➗", "d": "Divide" },
        { "c": "🟰", "d": "Equals" },
        { "c": "♾", "d": "Infinity" }
    ]
},
{
    "title": "Punctuation Symbols",
    "charSet": [
        { "c": "‼", "d": "Double exclamation" },
        { "c": "⁉", "d": "Exclamation and question mark" },
        { "c": "❓", "d": "Red question mark" },
        { "c": "❔", "d": "White question mark" },
        { "c": "❗", "d": "Red exclamation mark" },
        { "c": "❕", "d": "White exclamation mark" },
        { "c": "〰", "d": "Wavy dash" }
    ]
},
{
    "title": "Currency",
    "charSet": [
        { "c": "💱", "d": "Currency exchange" },
        { "c": "💲", "d": "Heavy green dollar sign" }
    ]
},
{
    "title": "Other Symbols",
    "charSet": [
        { "c": "⚕", "d": "Medical symbol" },
        { "c": "♻", "d": "Recycling symbol" },
        { "c": "⚜", "d": "Fleur-de-lis" },
        { "c": "🔱", "d": "Trident" },
        { "c": "📛", "d": "Name badge" },
        { "c": "🔰", "d": "Japanese symbol for beginner" },
        { "c": "⭕", "d": "Hollow red circle" },
        { "c": "✅", "d": "Green box with checkmark" },
        { "c": "☑", "d": "Blue box with checkmark" },
        { "c": "✔", "d": "Checkmark" },
        { "c": "❌", "d": "Crossmark" },
        { "c": "❎", "d": "Green crossmark" },
        { "c": "➰", "d": "Curly loop" },
        { "c": "➿", "d": "Double curly loop" },
        { "c": "〽", "d": "Part alternation mark" },
        { "c": "✳", "d": "Eight-spoked asterisk" },
        { "c": "✴", "d": "Eight-pointed star" },
        { "c": "❇", "d": "Sparkle" },
        { "c": "©", "d": "Copyright symbol" },
        { "c": "®", "d": "Registered" },
        { "c": "™", "d": "Trademark" }
    ]
},
{
    "title": "Keycap",
    "charSet": [
        { "c": "#️⃣", "d": "# Keycap" },
        { "c": "*️⃣", "d": "* Keycap" },
        { "c": "0️⃣", "d": "0 Keycap" },
        { "c": "1️⃣", "d": "1 Keycap" },
        { "c": "2️⃣", "d": "2 Keycap" },
        { "c": "3️⃣", "d": "3 Keycap" },
        { "c": "4️⃣", "d": "4 Keycap" },
        { "c": "5️⃣", "d": "5 Keycap" },
        { "c": "6️⃣", "d": "6 Keycap" },
        { "c": "7️⃣", "d": "7 Keycap" },
        { "c": "8️⃣", "d": "8 Keycap" },
        { "c": "9️⃣", "d": "9 Keycap" },
        { "c": "🔟", "d": "10 Keycap" }
    ]
},
{
    "title": "Alphanumeric Symbols",
    "charSet": [
        { "c": "🔠", "d": "Input Latin uppercase" },
        { "c": "🔡", "d": "Input Latin lowercase" },
        { "c": "🔢", "d": "Input numbers" },
        { "c": "🔣", "d": "Input symbols" },
        { "c": "🔤", "d": "Input Latin letters" },
        { "c": "🅰", "d": "A blood type" },
        { "c": "🆎", "d": "AB blood type" },
        { "c": "🅱", "d": "B blood type" },
        { "c": "🅾", "d": "O blood type" },
        { "c": "🆑", "d": "CL button" },
        { "c": "🆒", "d": "Cool button" },
        { "c": "🆓", "d": "Free button" },
        { "c": "ℹ", "d": "Info button" },
        { "c": "🆔", "d": "ID button" },
        { "c": "Ⓜ", "d": "Circled M" },
        { "c": "🆕", "d": "New button" },
        { "c": "🆖", "d": "NG button" },
        { "c": "🆗", "d": "OK button" },
        { "c": "🅿", "d": "P button" },
        { "c": "🆘", "d": "SOS button" },
        { "c": "🆙", "d": "UP! button" },
        { "c": "🆚", "d": "VS Button" }
    ]
},
{
    "title": "Japanese Buttons",
    "charSet": [
        { "c": "🈁", "d": "Japanese \"here\" button" },
        { "c": "🈂", "d": "Japanese \"service charge\" button" },
        { "c": "🈷", "d": "Japanese \"monthly amount\" button" },
        { "c": "🈶", "d": "Japanese \"not free of charge\" button" },
        { "c": "🈯", "d": "Japanese \"reserved\" button" },
        { "c": "🉐", "d": "Japanese \"bargain\" button" },
        { "c": "🈹", "d": "Japanese \"discount\" button" },
        { "c": "🈚", "d": "Japanese \"free of charge\" button" },
        { "c": "🈲", "d": "Japanese \"prohibited\" button" },
        { "c": "🉑", "d": "Japanese \"acceptable\" button" },
        { "c": "🈸", "d": "Japanese \"application\" button" },
        { "c": "🈴", "d": "Japanese \"passing grade\" button" },
        { "c": "🈳", "d": "Japanese \"vacancy\" button" },
        { "c": "㊗", "d": "Japanese \"congratulations\" button" },
        { "c": "㊙", "d": "Japanese \"secret\" button" },
        { "c": "🈺", "d": "Japanese \"open for business\" button" },
        { "c": "🈵", "d": "Japanese \"no vacancy\" button" }
    ]
},
{
    "title": "Geometric Emojis",
    "charSet": [
        { "c": "🔴", "d": "Red circle" },
        { "c": "🟠", "d": "Orange circle" },
        { "c": "🟡", "d": "Yellow circle" },
        { "c": "🟢", "d": "Green circle" },
        { "c": "🔵", "d": "Blue circle" },
        { "c": "🟣", "d": "Purple circle" },
        { "c": "🟤", "d": "Brown circle" },
        { "c": "⚫", "d": "Black circle" },
        { "c": "⚪", "d": "White circle" },
        { "c": "🟥", "d": "Red square" },
        { "c": "🟧", "d": "Orange square" },
        { "c": "🟨", "d": "Yellow square" },
        { "c": "🟩", "d": "Green square" },
        { "c": "🟦", "d": "Blue square" },
        { "c": "🟪", "d": "Purple square" },
        { "c": "🟫", "d": "Brown square" },
        { "c": "⬛", "d": "Black square" },
        { "c": "⬜", "d": "White square" },
        { "c": "🔶", "d": "Large orange diamond" },
        { "c": "🔷", "d": "Large blue diamond" },
        { "c": "🔸", "d": "Small orange diamond" },
        { "c": "🔹", "d": "Small blue diamond" },
        { "c": "🔺", "d": "Red triangle pointed up" },
        { "c": "🔻", "d": "Red triangle pointed down" },
        { "c": "💠", "d": "Diamond with a dot" },
        { "c": "🔘", "d": "Radio button" },
        { "c": "🔳", "d": "White square button" },
        { "c": "🔲", "d": "Black square button" }
    ]
},
{
    "title": "Flags",
    "charSet": [
        { "c": "🏁", "d": "Chequered flag" },
        { "c": "🚩", "d": "Triangular flag" },
        { "c": "🎌", "d": "Crossed flag" },
        { "c": "🏴", "d": "Black flag" },
        { "c": "🏳", "d": "White flag" },
        { "c": "🏳️‍🌈", "d": "Rainbow flag" },
        { "c": "🏳️‍⚧️", "d": "Transgender Flag" },
        { "c": "🏴‍☠️", "d": "Pirate flag" }
    ]
},
{
    "title": "Country Flags",
    "charSet": [
        { "c": "🇦🇨", "d": "Ascension Island flag" },
        { "c": "🇦🇩", "d": "Andorra flag" },
        { "c": "🇦🇪", "d": "UAE flag" },
        { "c": "🇦🇫", "d": "Afghanistan flag" },
        { "c": "🇦🇬", "d": "Antigua & Barbuda flag" },
        { "c": "🇦🇮", "d": "Anguilla flag" },
        { "c": "🇦🇱", "d": "Albania" },
        { "c": "🇩🇿", "d": "Algeria flag" },
        { "c": "🇦🇲", "d": "Armenia flag" },
        { "c": "🇦🇴", "d": "Angola flag" },
        { "c": "🇦🇶", "d": "Antarctica flag" },
        { "c": "🇦🇷", "d": "Argentina flag" },
        { "c": "🇦🇸", "d": "American Samoa flag" },
        { "c": "🇦🇹", "d": "Austria flag" },
        { "c": "🇦🇺", "d": "Australia flag" },
        { "c": "🇦🇼", "d": "Aruba flag" },
        { "c": "🇦🇽", "d": "Åland Islands flag" },
        { "c": "🇦🇿", "d": "Azerbaijan flag" },
        { "c": "🇧🇦", "d": "Bosnia & Herzegovina flag" },
        { "c": "🇧🇩", "d": "Bangladesh flag" },
        { "c": "🇧🇪", "d": "Belgium flag" },
        { "c": "🇧🇫", "d": "Burkina Faso flag" },
        { "c": "🇧🇬", "d": "Bulgaria flag" },
        { "c": "🇧🇭", "d": "Bahrain flag" },
        { "c": "🇧🇮", "d": "Burundi flag" },
        { "c": "🇧🇯", "d": "Benin Republic flag" },
        { "c": "🇧🇱", "d": "St. Barthélemy flag" },
        { "c": "🇧🇲", "d": "Bermuda flag" },
        { "c": "🇧🇳", "d": "Brunei flag" },
        { "c": "🇧🇴", "d": "Bolivia flag" },
        { "c": "🇧🇶", "d": "Caribbean Netherlands flag" },
        { "c": "🇧🇷", "d": "Brazil flag" },
        { "c": "🇧🇸", "d": "Bahamas flag" },
        { "c": "🇧🇹", "d": "Bhutan flag" },
        { "c": "🇧🇻", "d": "Bouvet Island flag" },
        { "c": "🇧🇼", "d": "Botswana flag" },
        { "c": "🇧🇾", "d": "Belarus flag" },
        { "c": "🇧🇿", "d": "Belize flag" },
        { "c": "🇨🇦", "d": "Canada flag" },
        { "c": "🇨🇨", "d": "Cocos (Keeling) Islands flag" },
        { "c": "🇨🇩", "d": "DR Congo flag" },
        { "c": "🇨🇫", "d": "Central African Republic flag" },
        { "c": "🇨🇬", "d": "Congo Brazzaville flag" },
        { "c": "🇨🇭", "d": "Switzerland flag" },
        { "c": "🇨🇮", "d": "Côte d’Ivoire flag" },
        { "c": "🇨🇰", "d": "Cook Islands flag" },
        { "c": "🇨🇱", "d": "Chile flag" },
        { "c": "🇨🇲", "d": "Cameroon flag" },
        { "c": "🇨🇳", "d": "China flag" },
        { "c": "🇨🇴", "d": "Columbia flag" },
        { "c": "🇨🇵", "d": "Clipperton Island flag" },
        { "c": "🇨🇷", "d": "Costa Rica flag" },
        { "c": "🇨🇺", "d": "Cuba flag" },
        { "c": "🇨🇻", "d": "Cape Verde flag" },
        { "c": "🇨🇼", "d": "Curaçao flag" },
        { "c": "🇨🇽", "d": "Christmas Island flag" },
        { "c": "🇨🇾", "d": "Cyprus flag" },
        { "c": "🇨🇿", "d": "Czech Republic flag" },
        { "c": "🇩🇪", "d": "Germany flag" },
        { "c": "🇩🇬", "d": "Diego Garcia flag" },
        { "c": "🇩🇯", "d": "Djibouti flag" },
        { "c": "🇩🇰", "d": "Denmark flag" },
        { "c": "🇩🇲", "d": "Dominica flag" },
        { "c": "🇩🇴", "d": "Dominican Republic flag" },
        { "c": "🇪🇦", "d": "Ceuta & Melilla flag" },
        { "c": "🇪🇨", "d": "Ecuador flag" },
        { "c": "🇪🇪", "d": "Estonia flag" },
        { "c": "🇪🇬", "d": "Egypt flag" },
        { "c": "🇪🇭", "d": "Western Sahara flag" },
        { "c": "🇪🇷", "d": "Eritre flag" },
        { "c": "🇪🇸", "d": "Spain flag" },
        { "c": "🇪🇹", "d": "Ethiopia flag" },
        { "c": "🇪🇺", "d": "European Union flag" },
        { "c": "🇫🇮", "d": "Finalnd flag" },
        { "c": "🇫🇯", "d": "Fiji Island flag" },
        { "c": "🇫🇰", "d": "Falkland Islands flag" },
        { "c": "🇫🇲", "d": "Micronesia flag" },
        { "c": "🇫🇴", "d": "Faroe Islands flag" },
        { "c": "🇫🇷", "d": "France flag" },
        { "c": "🇬🇦", "d": "Gabon flag" },
        { "c": "🇬🇧", "d": "United Kingdom flag" },
        { "c": "🇬🇩", "d": "Grenada flag" },
        { "c": "🇬🇪", "d": "Georgia flag" },
        { "c": "🇬🇫", "d": "French Guiana flag" },
        { "c": "🇬🇬", "d": "Guernsey flag" },
        { "c": "🇬🇭", "d": "Ghana flag" },
        { "c": "🇬🇮", "d": "Gibraltar flag" },
        { "c": "🇬🇱", "d": "Greenland flag" },
        { "c": "🇬🇲", "d": "Gambia flag" },
        { "c": "🇬🇳", "d": "Guinea flag" },
        { "c": "🇬🇵", "d": "Guadeloupe flag" },
        { "c": "🇬🇶", "d": "Equatorial Guinea flag" },
        { "c": "🇬🇷", "d": "Greece flag" },
        { "c": "🇬🇸", "d": "South Georgia & South Sandwich Islands flag" },
        { "c": "🇬🇹", "d": "Guatemala flag" },
        { "c": "🇬🇺", "d": "Guam flag" },
        { "c": "🇬🇼", "d": "Guinea Bissau flag" },
        { "c": "🇬🇾", "d": "Guyana flag" },
        { "c": "🇭🇰", "d": "Hong Kong SAR China flag" },
        { "c": "🇭🇲", "d": "Heard & McDonald Islands flag" },
        { "c": "🇭🇳", "d": "Honduras flag" },
        { "c": "🇭🇷", "d": "Croatia flag" },
        { "c": "🇭🇹", "d": "Haiti flag" },
        { "c": "🇭🇺", "d": "Hungary flag" },
        { "c": "🇮🇨", "d": "Canary Islands flag" },
        { "c": "🇮🇩", "d": "Indonesia flag" },
        { "c": "🇮🇪", "d": "Ireland flag" },
        { "c": "🇮🇱", "d": "Israel flag" },
        { "c": "🇮🇲", "d": "Isle of Man flag" },
        { "c": "🇮🇳", "d": "India flag" },
        { "c": "🇮🇴", "d": "British Indian Ocean Territory flag" },
        { "c": "🇮🇶", "d": "Iraq flag" },
        { "c": "🇮🇷", "d": "Iran flag" },
        { "c": "🇮🇸", "d": "Iceland flag" },
        { "c": "🇮🇹", "d": "Italy flag" },
        { "c": "🇯🇪", "d": "Jersey flag" },
        { "c": "🇯🇲", "d": "Jamaica flag" },
        { "c": "🇯🇴", "d": "Jordan flag" },
        { "c": "🇯🇵", "d": "Japan flag" },
        { "c": "🇰🇪", "d": "Kenya flag" },
        { "c": "🇰🇬", "d": "Kyrgyzstan flag" },
        { "c": "🇰🇭", "d": "Cambodia flag" },
        { "c": "🇰🇮", "d": "Kiribati flag" },
        { "c": "🇰🇲", "d": "Comoros flag" },
        { "c": "🇰🇳", "d": "St. Kitts & Nevis flag" },
        { "c": "🇰🇵", "d": "North Korea flag" },
        { "c": "🇰🇷", "d": "South Korea flag" },
        { "c": "🇰🇼", "d": "Kuwait flag" },
        { "c": "🇰🇾", "d": "Cayman Islands flag" },
        { "c": "🇰🇿", "d": "Kazakhstan flag" },
        { "c": "🇱🇦", "d": "Laos flag" },
        { "c": "🇱🇧", "d": "Lebanon flag" },
        { "c": "🇱🇨", "d": "St. Lucia flag" },
        { "c": "🇱🇮", "d": "Liechtenstein flag" },
        { "c": "🇱🇰", "d": "Sri Lanka flag" },
        { "c": "🇱🇷", "d": "Liberia flag" },
        { "c": "🇱🇸", "d": "Lesotho flag" },
        { "c": "🇱🇹", "d": "Lithuania flag" },
        { "c": "🇱🇺", "d": "Luxembourg flag" },
        { "c": "🇱🇻", "d": "Latvia flag" },
        { "c": "🇱🇾", "d": "Libya flag" },
        { "c": "🇲🇦", "d": "Morocco flag" },
        { "c": "🇲🇨", "d": "Monaco flag" },
        { "c": "🇲🇩", "d": "Moldova flag" },
        { "c": "🇲🇪", "d": "Montenegro flag" },
        { "c": "🇲🇫", "d": "St. Martin flag" },
        { "c": "🇲🇬", "d": "Madagascar flag" },
        { "c": "🇲🇭", "d": "Marshall Islands flag" },
        { "c": "🇲🇰", "d": "North Macedonia flag" },
        { "c": "🇲🇱", "d": "Mali flag" },
        { "c": "🇲🇲", "d": "Myanmar flag" },
        { "c": "🇲🇳", "d": "Mongolia flag" },
        { "c": "🇲🇴", "d": "Macao SAR China flag" },
        { "c": "🇲🇵", "d": "Northern Mariana Islands flag" },
        { "c": "🇲🇶", "d": "Martinique flag" },
        { "c": "🇲🇷", "d": "Mauritania flag" },
        { "c": "🇲🇸", "d": "Montserrat flag" },
        { "c": "🇲🇹", "d": "Malta flag" },
        { "c": "🇲🇺", "d": "Mauritius flag" },
        { "c": "🇲🇻", "d": "Maldives flag" },
        { "c": "🇲🇼", "d": "Malawi flag" },
        { "c": "🇲🇽", "d": "Mexico flag" },
        { "c": "🇲🇾", "d": "Malaysia flag" },
        { "c": "🇲🇿", "d": "Mozambique flag" },
        { "c": "🇳🇦", "d": "Namibia flag" },
        { "c": "🇳🇨", "d": "New Caledonia flag" },
        { "c": "🇳🇪", "d": "Niger Republic flag" },
        { "c": "🇳🇬", "d": "Nigeria flag" },
        { "c": "🇳🇫", "d": "Norfolk Island flag" },
        { "c": "🇳🇮", "d": "Nicaragua flag" },
        { "c": "🇳🇱", "d": "Netherlands flag" },
        { "c": "🇳🇴", "d": "Norway flag" },
        { "c": "🇳🇵", "d": "Nepal flag" },
        { "c": "🇳🇷", "d": "Nauru flag" },
        { "c": "🇳🇺", "d": "Niue flag" },
        { "c": "🇳🇿", "d": "New Zealand flag" },
        { "c": "🇴🇲", "d": "Oman flag" },
        { "c": "🇵🇦", "d": "Panama flag" },
        { "c": "🇵🇪", "d": "Peru flag" },
        { "c": "🇵🇫", "d": "French Polynesia flag" },
        { "c": "🇵🇬", "d": "Papua New Guinea flag" },
        { "c": "🇵🇭", "d": "Philippines flag" },
        { "c": "🇵🇰", "d": "Pakistan flag" },
        { "c": "🇵🇱", "d": "Poland flag" },
        { "c": "🇵🇲", "d": "St. Pierre & Miquelon flag" },
        { "c": "🇵🇳", "d": "itcairn Islands flag" },
        { "c": "🇵🇷", "d": "Puerto Rico flag" },
        { "c": "🇵🇸", "d": "Palestinian Territories flag" },
        { "c": "🇵🇹", "d": "Portugal flag" },
        { "c": "🇵🇼", "d": "Palau flag" },
        { "c": "🇵🇾", "d": "Paraguay flag" },
        { "c": "🇶🇦", "d": "Qatar flag" },
        { "c": "🇷🇪", "d": "Réunion flag" },
        { "c": "🇷🇴", "d": "Romania flag" },
        { "c": "🇷🇸", "d": "Serbia flag" },
        { "c": "🇷🇺", "d": "Russia flag" },
        { "c": "🇷🇼", "d": "Rwanda flag" },
        { "c": "🇸🇦", "d": "Saudi Arabia flag" },
        { "c": "🇸🇧", "d": "Solomon Islands flag" },
        { "c": "🇸🇨", "d": "Seychelles flag" },
        { "c": "🇸🇩", "d": "Sudan flag" },
        { "c": "🇸🇪", "d": "Sweden flag" },
        { "c": "🇸🇬", "d": "Singapore flag" },
        { "c": "🇸🇭", "d": "St. Helena flag" },
        { "c": "🇸🇮", "d": "Slovenia flag" },
        { "c": "🇸🇯", "d": "Svalbard & Jan Mayen flag" },
        { "c": "🇸🇰", "d": "Slovakia flag" },
        { "c": "🇸🇱", "d": "Sierra Leone flag" },
        { "c": "🇸🇲", "d": "San Marino flag" },
        { "c": "🇸🇳", "d": "Senegal flag" },
        { "c": "🇸🇴", "d": "Somalia flag" },
        { "c": "🇸🇷", "d": "Suriname flag" },
        { "c": "🇸🇸", "d": "South Sudan flag" },
        { "c": "🇸🇹", "d": "São Tomé & Príncipe flag" },
        { "c": "🇸🇻", "d": "El Salvador flag" },
        { "c": "🇸🇽", "d": "Saint Maarten flag" },
        { "c": "🇸🇾", "d": "Syria flag" },
        { "c": "🇸🇿", "d": "Eswatini flag" },
        { "c": "🇹🇦", "d": "Tristan da Cunha flag" },
        { "c": "🇹🇨", "d": "Turks & Caicos Islands flag" },
        { "c": "🇹🇩", "d": "Chad flag" },
        { "c": "🇹🇫", "d": "French Southern Territories flag" },
        { "c": "🇹🇬", "d": "Togo flag" },
        { "c": "🇹🇭", "d": "Thailand flag" },
        { "c": "🇹🇯", "d": "Tajikistan flag" },
        { "c": "🇹🇰", "d": "Tokelau flag" },
        { "c": "🇹🇱", "d": "Timor-Leste flag" },
        { "c": "🇹🇲", "d": "Turkmenistan flag" },
        { "c": "🇹🇳", "d": "Tunisia flag" },
        { "c": "🇹🇴", "d": "Tonga flag" },
        { "c": "🇹🇷", "d": "Turkey flag" },
        { "c": "🇹🇹", "d": "Trinidad & Tobago flag" },
        { "c": "🇹🇻", "d": "Tuvalu flag" },
        { "c": "🇹🇼", "d": "Taiwan flag" },
        { "c": "🇹🇿", "d": "Tanzania flag" },
        { "c": "🇺🇦", "d": "Ukraine flag" },
        { "c": "🇺🇬", "d": "Uganda flag" },
        { "c": "🇺🇲", "d": "U.S. Outlying Islands flag" },
        { "c": "🇺🇳", "d": "United Nations flag" },
        { "c": "🇺🇸", "d": "United States flag" },
        { "c": "🇺🇾", "d": "Uruguay flag" },
        { "c": "🇺🇿", "d": "Uzbekistan flag" },
        { "c": "🇻🇦", "d": "Vatican City flag" },
        { "c": "🇻🇨", "d": "St. Vincent & Grenadines flag" },
        { "c": "🇻🇪", "d": "Venezuela flag" },
        { "c": "🇻🇬", "d": "British Virgin Islands flag" },
        { "c": "🇻🇮", "d": "U.S. Virgin Islands flag" },
        { "c": "🇻🇳", "d": "Vietnam flag" },
        { "c": "🇻🇺", "d": "Vanuatu flag" },
        { "c": "🇼🇫", "d": "Wallis & Futuna flag" },
        { "c": "🇼🇸", "d": "Samoa flag" },
        { "c": "🇽🇰", "d": "Kosovo flag" },
        { "c": "🇾🇪", "d": "Yemen flag" },
        { "c": "🇾🇹", "d": "Mayotte flag" },
        { "c": "🇿🇦", "d": "South Africa flag" },
        { "c": "🇿🇲", "d": "Zambia flag" },
        { "c": "🇿🇼", "d": "Zimbabwe flag" },
        { "c": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "d": "England flag" },
        { "c": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "d": "Scotland flag" },
        { "c": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "d": "Wales flag" }
    ]
}];
