export const ADD_SYMBOL = Symbol('add a symbol'),
    ALIGN_H = Symbol('align horizontally'),
    ALIGN_V = Symbol('align vertically'),
    BULK_ALIGNV = Symbol('bulk vertical align'),
    BULK_ALIGNH = Symbol('bulk horizontal align'),
    BULK_SPACE= Symbol('bulk horiz / vert space'),
    BULK_DELETE = Symbol('bulk delete'),
    BULK_CENTER_VERTICALLY = Symbol('bulk center vertically'),
    BULK_CENTER_HORIZONALLY = Symbol('bulk center horizontally'),
    CAN_SCROLL_SYMBOLS = Symbol('when focused on a wheel'),
    CLONE_SYMBOL = Symbol('clone a symbol'),
    COLLAPSE_FAMILY = Symbol('collapse family'),
    EXPAND_FAMILY = Symbol('expand family'),
    FOCUS_ON_SYMBOL = Symbol('focus on one symbol'),
    IMPORT = Symbol('import'),
    IMPORT_KEYFRAMES = Symbol('import keyframes'),
    INIT = Symbol('init'),
    INIT_VIEWPORT = Symbol('init sizes'),
    LET_ASCIIPANEL_OPEN_AFTER_SELECTION = Symbol('let the panel open after selection'),
    MAX_ZI = Symbol('maximize z index'),
    MIN_ZI = Symbol('minimize z-index'),
    MOVE_ALL_SYMBOLS = Symbol('global move'),
    MOVE_SYMBOL = Symbol('move up down symbol'),
    MOVE_TARGET_ONE_PX = Symbol('move 1px symbol in direction'),
    NEW = Symbol('new creativity'),
    NEW_KEY_FRAME = Symbol('save a new keyframe'),
    PAN_ALL_SYMBOLS = Symbol('global pan'),
    REMOVE_ALL_KEY_FRAMES = Symbol('delete all keyframe'),
    REMOVE_ERROR = Symbol('remove error'),
    REMOVE_KEY_FRAME = Symbol('delete a  keyframe'),
    REMOVE_SYMBOL = Symbol('remove a symbol'),
    RESIZE = Symbol('resize'),
    SET_ASCIIPANEL_FILTER = Symbol('set asciipanel filter'),
    SET_SYMBOLS_FILTER = Symbol('set symbols filter'),
    SWITCH_SYMBOL = Symbol('switch_symbol'),
    SWITCH_THEME = Symbol('switch theme'),
    SYMBOL_FOCUS = Symbol('focus symbol toggle'),
    SWAP_SYMBOL = Symbol('swap a symbol'),
    TOGGLE_ADD_PANEL = Symbol('toggle add panel'),
    TOGGLE_ITALIC = Symbol('toggle italic'),
    TOGGLE_PANEL = Symbol('toggle panel'),
    TOGGLE_SYMBOL_SELECTION = Symbol('select toggle symbol for bulk action'),
    TOGGLE_SYMBOLS_SELECTION = Symbol('select toggle symbols'),
    TUNE_SYMBOL_POSITION = Symbol('tune symbol position'),
    UNDO = Symbol('undo'),
    UPDATE_GLOBAL = Symbol('update first level field panel'),
    UPDATE_KEY_FRAME = Symbol('uodate a new keyframe'),
    UPDATE_SYMBOL = Symbol('update a symbol'),
    UPDATE_SYMBOL_USLIDER = Symbol('update a symbol with uslider'),
    ZOOM_IN = Symbol('zoom in'),
    ZOOM_OUT = Symbol('zoom out'),
    ZOOM_ZERO = Symbol('zoom zero'),
    SAVE_SCROLL = Symbol('save scroll');

const exp = {
    ADD_SYMBOL,
    ALIGN_H,
    ALIGN_V,
    BULK_ALIGNV,
    BULK_ALIGNH,
    BULK_SPACE,
    BULK_DELETE,
    BULK_CENTER_VERTICALLY,
    BULK_CENTER_HORIZONALLY,
    CAN_SCROLL_SYMBOLS,
    CLONE_SYMBOL,
    COLLAPSE_FAMILY,
    EXPAND_FAMILY,
    FOCUS_ON_SYMBOL,
    IMPORT,
    IMPORT_KEYFRAMES,
    INIT,
    INIT_VIEWPORT,
    LET_ASCIIPANEL_OPEN_AFTER_SELECTION,
    MAX_ZI,
    MIN_ZI,
    MOVE_ALL_SYMBOLS,
    MOVE_SYMBOL,
    MOVE_TARGET_ONE_PX,
    NEW,
    NEW_KEY_FRAME,
    PAN_ALL_SYMBOLS,
    REMOVE_ALL_KEY_FRAMES,
    REMOVE_ERROR,
    REMOVE_KEY_FRAME,
    REMOVE_SYMBOL,
    RESIZE,
    SET_ASCIIPANEL_FILTER,
    SET_SYMBOLS_FILTER,
    SWITCH_SYMBOL,
    SWITCH_THEME,
    SYMBOL_FOCUS,
    SWAP_SYMBOL,
    TOGGLE_ADD_PANEL,
    TOGGLE_ITALIC,
    TOGGLE_PANEL,
    TOGGLE_SYMBOL_SELECTION,
    TOGGLE_SYMBOLS_SELECTION,
    TUNE_SYMBOL_POSITION,
    UNDO,
    UPDATE_GLOBAL,
    UPDATE_KEY_FRAME,
    UPDATE_SYMBOL,
    UPDATE_SYMBOL_USLIDER,
    ZOOM_IN,
    ZOOM_OUT,
    ZOOM_ZERO,
    SAVE_SCROLL
};

export default exp;